### ISSUE TITLE
Error NodeMCU

### ISSUE THREAD

**Issue by Reniertjes** [scottlawsonbc/audio-reactive-led-strip#100]
After setting up all the programs my nodemcu gives the following error over serial;

```
Connected to [my network]
IP address: [given ip]

Exception (29):
epc1=0x402021b4 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00644100 depc=0x00000000

ctx: cont 
sp: 3fff0280 end: 3fff0480 offset: 01a0

>>>stack>>>
3fff0420:  3ffe8e98 4e02a8c0 00000064 40203560  
3fff0430:  5c008d6c 744f0086 00644100 27005433  
3fff0440:  351d0044 00281400 09001d0e 0e060014  
3fff0450:  3fffdad0 3ffeeea4 3ffeed30 3ffeed30  
3fff0460:  3fffdad0 00000000 3ffef448 40203534  
3fff0470:  feefeffe feefeffe 3ffef460 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v60000b00
~ld
þ
6
.
```
Where can i find what this output means? Or is there somebody who can tell me?

**Comment by not-matt** [comment]
Weird error, never seen it before. Are all the settings for the NodeMCU the [same as they are here](https://imgur.com/a/I6Ckj)?

**Comment by Reniertjes** [comment]
Exactly the same yes..

**Comment by joeybab3** [comment]
I used to get this all the time. It doesn’t make any sense what causes it but it makes it basically unusable.

**Comment by joeybab3** [comment]
Try some different ways or powering it, and try formatting it entirely then reuploading, that usually works for me.

**Comment by scottlawsonbc** [comment]
This means a fatal error occurred on the ESP and watchdog timer was forced to reset the chip. Can you please paste the Arduino firmware here and I'll see if I can figure out what happened.

**Comment by joeybab3** [comment]
It happens with my fork, and yours if that helps

**Comment by Reniertjes** [comment]
Thanks for wanting to help! Maybe to clarify the problem some more, when i start the nodemcu and open serial I get to see FPS:0. Only after it starts receiving packages it gives this fatal error.
The code I use is the code from this page, the only things I changed are the number of leds, SSID, password, ip and gateway. 

`
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <WebSocketsServer.h>
#include <Hash.h>
#include <WiFiUdp.h>
#include "ws2812_i2s.h"

// Set to the number of LEDs in your LED strip
#define NUM_LEDS 30
// Maximum number of packets to hold in the buffer. Don't change this.
#define BUFFER_LEN 1024
// Toggles FPS output (1 = print FPS over serial, 0 = disable output)
#define PRINT_FPS 1

// Wifi and socket settings
const char* ssid     = "[My network]";
const char* password = "[My password]";
unsigned int localPort = 7777;
char packetBuffer[BUFFER_LEN];

// LED strip
static WS2812 ledstrip;
static Pixel_t pixels[NUM_LEDS];
WiFiUDP port;

// Network information
// IP must match the IP in config.py
IPAddress ip(192, 168, 2, 150);
// Set gateway to your router's gateway
IPAddress gateway(192, 168, 2, 254);
IPAddress subnet(255, 255, 255, 0);

void setup() {
    Serial.begin(115200);
    WiFi.config(ip, gateway, subnet);
    WiFi.begin(ssid, password);
    Serial.println("");
    // Connect to wifi and print the IP address over serial
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.println("");
    Serial.print("Connected to ");
    Serial.println(ssid);
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());
    port.begin(localPort);
    ledstrip.init(NUM_LEDS);
}

uint8_t N = 0;
#if PRINT_FPS
    uint16_t fpsCounter = 0;
    uint32_t secondTimer = 0;
#endif

void loop() {
    // Read data over socket
    int packetSize = port.parsePacket();
    // If packets have been received, interpret the command
    if (packetSize) {
        int len = port.read(packetBuffer, BUFFER_LEN);
        for(int i = 0; i < len; i+=4) {
            packetBuffer[len] = 0;
            N = packetBuffer[i];
            pixels[N].R = (uint8_t)packetBuffer[i+1];
            pixels[N].G = (uint8_t)packetBuffer[i+2];
            pixels[N].B = (uint8_t)packetBuffer[i+3];
        } 
        ledstrip.show(pixels);
        #if PRINT_FPS
            fpsCounter++;
        #endif
    }
    #if PRINT_FPS
        if (millis() - secondTimer >= 1000U) {
            secondTimer = millis();
            Serial.printf("FPS: %d\n", fpsCounter);
            fpsCounter = 0;
        }   
    #endif
}
`

**Comment by kwrngu** [comment]
i experience this. this is because your config.py led number not same as the esp script led number

**Comment by Reniertjes** [comment]
Amazing, it works! Thanks all!
