### ISSUE TITLE
it's bumping itself up during silence

### ISSUE THREAD

**Issue by relax81** [scottlawsonbc/audio-reactive-led-strip#102]
After some trouble i got it working on my pc and nodemcu, but for some reason I've the problem that the visualization is bumping itself up during silence. It looks like it's calibrating / normalizing itself when audio output happens, but once a few seconds of silence come it bumps itself up, detects an audio input that doesn't exist (the windows audio mixer shows also silence) and the leds go crazy. This happens with a microphone as well as direct sound mixer input. 

Has anyone found a similar and more recent project?

**Comment by not-matt** [comment]
Adjust MIN_VOLUME_THRESHOLD in config.py to a higher value. I find 1e-3
works well, but it will depend on your microphone/sound card.

**Comment by relax81** [comment]
Thank you, that change helped a lot.
 I've also installed the VoiceMeeter application now as well which helps to have a bit better control over my usb audio device.
