### ISSUE TITLE
nodeMCU does not connect over wifi

### ISSUE THREAD

**Issue by mando34** [scottlawsonbc/audio-reactive-led-strip#103]
First off, Im pretty much a noob, so im a little lost troubleshooting. I think i got all the code right but when I run the code. it will run properly, but the light strip will not light up. but when i connect the board to the computer and run the visualization the led lights up like its supposed to. can somebody tell me where i messed up

**Comment by relax81** [comment]
Are you sure that it has enough power? 

When it's connected to your compuer you can open the serial monitor in the arduino ide (ctrl+shift+m). push the reset button on the nodeMCU and check the output. It should tell you if the wifi connection works or not.

**Comment by not-matt** [comment]
Sounds like a wireless configuration issue. Things to check, in this order:

1 - Is the device properly configured to connect to the network? (look in ws2812_controller.ide)
2 - Do you have the correct IP address for the device? (look at your router's configuration page for devices on the network)
3 - Can the computer communicate with the device? (ping the device using its IP address)
4 - Have you got the correct IP address in config.py? (needs to match that in ws2812_controller.ide)

**Comment by mando34** [comment]
The device is correct both in the ws2812_controller and in the config.py file. The device also shows up in the routers list of devices, but when i ping the device from my computer it doesn't connect.
