### ISSUE TITLE
Adafruit neopixel library?

### ISSUE THREAD

**Issue by joeybab3** [scottlawsonbc/audio-reactive-led-strip#11]
Originally when I first tried to set this up, I could only get adafruit/neopixel examples working with my strip. I ended up remaking the code for that library and I was wondering if you wanted me to also add a neopixel example (makes it much simpler as there aren't 8 files with every sketch)

**Comment by scottlawsonbc** [comment]
I'd like to only have one version of the ESP8266 firmware to keep things simple. I'm open to the possibility of replacing the ws2812_i2s library with another library such as FastLED.

The only concern I have about switching to another library is performance. Have you noticed any problems with refresh rate when using the neopixel library? If that seems to work then I'd like to try using the FastLED library.

**Comment by joeybab3** [comment]
I didnt see any even with 250 leds. I'll update my pull request and just make it use WiFiManager and responding by default if you want to only have one firmware

**Comment by Atraii** [comment]
The [NeoPixelBus](https://github.com/Makuna/NeoPixelBus/wiki) library is a feature complete replacement of the NeoPixel library except it uses DMA or UART instead of bit banging output. However, the quick math libraries in FastLED are extremely useful. I tend to make use of the FastLED library and then use NeoPixelBus to output to the strip.

**Comment by scottlawsonbc** [comment]
I'm convinced. Let's move away from the current library and replace it with NeoPixelBus.

I'll leave this issue open until the change has been made. The README documentation will need to be updated as well.

Unfortunately I won't get a chance to do this for a while, but I'd be happy to consider a pull request.

**Comment by joeybab3** [comment]
Sorry, I've been swamped and completely forgot about this, are you still interested in replacing the current ws2812 library with the neopixelbus one? If so, I will get to work with a PR for you. 

Also not related but possibly still of use:
I have successfully tested the firmware on the wemos d1 mini and wemos d1, using the rx/d0 pin if you want to add that to the readme.

**Comment by scottlawsonbc** [comment]
Yes please. If you make those changes put them in separate pull requests

**Comment by joeybab3** [comment]
I wrote the whole thing in about 10 minutes in one go... I don't know why I kept putting this off.
