### ISSUE TITLE
make wifi bridge between phone and mobile 

### ISSUE THREAD

**Issue by mkeyno** [scottlawsonbc/audio-reactive-led-strip#111]
sorry to open ticket for my question, actually I've plan to make wifi bridge (ESP8266) between my landline phone and my smart mobile , so I could dial or receive my phone by mobile , I'm not sure about the which hardware should be selected and really appreciated to have your probably advise for that

**Comment by not-matt** [comment]
You're really asking in the wrong place. Maybe something like [this](https://www.invoxia.com/eu/en/mobile-landline/voice-bridge) is what you're looking for? I'm not affiliated, but it's the top result when I search "landline mobile wifi bridge".

**Comment by joeybab3** [comment]
I would suggest posting this on a forum devoted to esp8266 questions, as this is more meant for this specific software.
