### ISSUE TITLE
Help me setup...This is super awsome project😍 

### ISSUE THREAD

**Issue by VizzZ13** [scottlawsonbc/audio-reactive-led-strip#113]
3 questions.. 😅 (for Pc&Esp8266)
1.Can someone make a video or else show step by step instructions.? 
2.Can u show a real image of your Circuit with all connections.? 
3.Is 5v wall power adapter with screw jack adapter enough to power 4m 60led strip?

**Comment by not-matt** [comment]
Regarding #1&2, have a proper read through the README.md. I can't think of anything you need to get it set up that you wouldn't find there.

Regarding #3, you'll have to give some more info. How many amps can it provide? Do you have 60 LEDs total?

Read through these tutorials regarding [best practices](https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices) and [powering](https://learn.adafruit.com/adafruit-neopixel-uberguide/powering-neopixels) your led strip.

**Comment by VizzZ13** [comment]
I dont know how to setup the circuits. I dont know anything about electronics.. I'm doing research for 2 days about this project from different sites but still not enough infomation to setup this connections. An image would be helpful for me to figure it out🤗. Regarding 3. I ordered 4 meter long 60 leds /meter.how much power supply should i buy.??

**Comment by rbirkby** [comment]
In case anyone wants to see what I did with this over a year ago:
https://github.com/rbirkby/aws-infra/blob/master/content/visualization-skill.md
https://www.youtube.com/watch?v=lj1yhpyGnT4

**Comment by not-matt** [comment]
@VizzZ13 Email me at u3449121@mvrht.net if you want a hand.

**Comment by VizzZ13** [comment]
Yes I want help.. i was. Asleep(sry😅😅)

**Comment by VizzZ13** [comment]
The led strip has 3 wires and extra 2 wires for power supply. In this 3 wires the data in pin goes to Rx pin of (Esp8266 nodeMcu v3) and where the remaining 2 wires go?? which pins?? And should I give power to Esp8266? or the USB power is enough for the Esp to work??

**Comment by joeybab3** [comment]
The red one goes to +5v and the black/white/other color goes into ground. 4m and 60 leds will need external power.

**Comment by VizzZ13** [comment]
@joeybab3. Does the red wire gives power to the ESP?? or does it takes power from Esp to Led strip??

**Comment by joeybab3** [comment]
I use it to give power to the led strip and the esp on strips that have more than like 30 leds
