### ISSUE TITLE
Set brightness for ESP8266

### ISSUE THREAD

**Issue by shijilt** [scottlawsonbc/audio-reactive-led-strip#114]
in the config file, I can see option to set brightness level for pi, but how to set brightness for ESP8266 ?

**Comment by d-rez** [comment]
You could run a matrix operation to multiply color values by e.g. 0.5 (in the python code)

**Comment by d-rez** [comment]
You could run a matrix operation to multiply color values by e.g. 0.5 (in the python code) or [implement your own protocol ](https://www.youtube.com/watch?v=FoTgSMvDpUw) that would allow brightness controls

**Comment by not-matt** [comment]
Will be implemented soon 👌

**Comment by TheUNkilled123** [comment]
So can anyone provide more input on this as my strip is running kinda hot and it's really bright so I can't use the default values?
How would you go about adding a matrix operation to the python code?

**Comment by joeybab3** [comment]
The original question seems to have been answered, if anyone is looking for more help on this feel free to open a new issue.
