### ISSUE TITLE
How connect 2 LED strip ?

### ISSUE THREAD

**Issue by mariangigabyte** [scottlawsonbc/audio-reactive-led-strip#115]
for a room i need mor LEDs. if the maximum of 256 LEDs is not cover entire room

**Comment by ItsTheJetstream** [comment]
@mariangigabyte You could try to have multiple ESPs on different IPs and then modifiy the visualization.py (and corresponding files) to output to both IPs. I was also thinking about something like this and will modify the code to output to more than one ESP8266 / ESP32.

**Comment by not-matt** [comment]
Working on it 👌

**Comment by blassbasti** [comment]
@not-matt did it work out?

**Comment by mariangigabyte** [comment]
No :(

**Comment by not-matt** [comment]
That's done, it's on my repo

**Comment by mariangigabyte** [comment]
Where?

**Comment by mariangigabyte** [comment]
Where?

**Comment by not-matt** [comment]
Go to my profile, look for "Systematic LEDs"

**Comment by blassbasti** [comment]
well I already looked into your project and it's awesome!
maybe it's the wrong place here to talk about this but I am not able to find the line in the code of your repo to use multiple led strips with different esp8266...

**Comment by mariangigabyte** [comment]
How much leds can I put there?
