### ISSUE TITLE
In the section of Configure the visualization code - cant find config.py file 

### ISSUE THREAD

**Issue by Yariv-h** [scottlawsonbc/audio-reactive-led-strip#117]
In this section it says that i have to edit the config.py file

this is the only thing i have on the systme:

osmc@led:~/rpi_ws281x/python/examples$ sudo find / -name "config.py"
/usr/lib/python2.7/distutils/config.py
/usr/lib/python2.7/distutils/command/config.py
/usr/lib/python2.7/logging/config.py

**Comment by Yariv-h** [comment]
Just now figured it out, this step was actually missing for the RP part :)

**Comment by ItsTheJetstream** [comment]
@Yariv-h couldyou close this issue then? 😄
