### ISSUE TITLE
Setting up the visualizer

### ISSUE THREAD

**Issue by ItsTheJetstream** [scottlawsonbc/audio-reactive-led-strip#125]
I am pretty new to electronics and arduino projects in particular.
Right now what I have is a LED strip with 45 LEDs. Right now I am trying to power these of a 5V USB wall plug that should provide about enough to make this work.
I have connected the +5V of the strip to the USBs 5V and the GND of the Strip to the GND of the USB plug.

Now I set up the code in python and Arduino and want to start the visualizaion. But I have a few questions:
1. how do I flash the ESP8266 correctly, mine has a "Flash"-labeled button - do I need to press it all the time while uploading the code?
2. Hoe do I connect the ESP8266 to the LED? I dont think that I could just hook up the ESPs RX to the DIN of the LED and powering it off another power source than the strip itself, that would be no common ground. However, I dont know how to connect them properly together.

Thanks for any help!

EDIT 1: My module is the NodeMCU Lua Amica Module V2 ESP8266 ESP-12E.

**Comment by ItsTheJetstream** [comment]
After some fiddling around I can say what worked for me:
1. Holding the Flash button the whole time while it flashes works for me.
2. They dont exactly need the same GND connection, as I was able to simply add the wire from the RX pin to the DIN of the strip, however I now have the problem that there is always flashign of the leds. I don't know if that has somethign to do with that.

**Comment by ItsTheJetstream** [comment]
Using the Vin and GND pin of my Node MCU I could also resolve this problem, I will maybe make a guide on how to build something like this so others don't run into the same problem as me. Thinking about it afterwards, all questions were pretty silly but for people not knowing a thing about how electronics work it could be a nice touch to make a video / even more detailed written guide with images showing the steps in detail.

**Comment by not-matt** [comment]
I imagine a step by step setup guide would be appreciated by a lot of
people 👍
