### ISSUE TITLE
Artnet output?

### ISSUE THREAD

**Issue by gaijinsr** [scottlawsonbc/audio-reactive-led-strip#134]
Hi Scott,
thanks for sharing your work, I have been looking for something like this for quite some time!
Have you thought about adding support for Artnet in addition to your own protocol for sending data to the ESP8266? The changes should be rather minor (the protocol is quite simple), and this would make it much easier to integrate your software into existing installations.
Best,     Stefan

**Comment by gaijinsr** [comment]
Hi,
I actually looked into Artnet a bit last night. The protocol is really simple and I managed to write a simple python program to control a LED strip connected to EspLightNode by Frans-Willem. I then proceeded to implement this as an additional output in led.py. There are just a few additional lines (some of them are even copied from your code), but the Artnet connection works perfectly! The IP address is hard-coded into led.py and at the moment the code supports only 255 channels (this limitation could easily be removed, but my strip only has 64 LEDs). Also, I always send "01" as the sequence number, but if somebody ever encounters a device that actually requires increasing sequence numbers, this could also be easily implemented.
You are welcome to integrate this into your code.
Best,   Stefan

$ diff led.py led.py-orig
33,39d32
< elif config.DEVICE == 'artnet':
<     import socket
<     UDP_IP = "192.168.2.89"
<     UDP_PORT = 6454
<     #          A r t - N e t    Header     seq  phys  univ  length high byte
<     HEADER = "4172742d4e6574"+"000050000e"+"01"+"00"+"0000"+"00"
<     sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
144,165d136
< def _update_artnet():
<     """Writes new LED values to Artnet - SR 14Mar18
<        ToDo: Read IP address from config, properly calculate packet length if config.N_PIXELS*3 > 255
<     """
<     global pixels
<
<     # Truncate values and cast to integer
<     pixels = np.clip(pixels, 0, 255).astype(int)
<     # Optional gamma correction
<     p = _gamma[pixels] if config.SOFTWARE_GAMMA_CORRECTION else np.copy(pixels)
<     # Read the rgb values
<     r = p[0][:].astype(int)
<     g = p[1][:].astype(int)
<     b = p[2][:].astype(int)
<
<     # now assemble the DMX data
<     DATA = ""
<     for i in range(config.N_PIXELS):
<         DATA = DATA + chr(r[i]) + chr(g[i]) + chr(b[i])
<     # send data
<     sock.sendto(bytearray.fromhex(HEADER)+chr(3*config.N_PIXELS)+DATA, (UDP_IP, UDP_PORT))
<
175,176d145
<     elif config.DEVICE == 'artnet':
<         _update_artnet() 

[led.py.txt](https://github.com/scottlawsonbc/audio-reactive-led-strip/files/1810363/led.py.txt)

**Comment by DatanoiseTV** [comment]
I've just contributed this in #288
