### ISSUE TITLE
WS2801 possible?

### ISSUE THREAD

**Issue by mischa67** [scottlawsonbc/audio-reactive-led-strip#135]
Hi,

is it possible to use this project with an WS2801 LED stripe on Raspberry Pi?

Thank You
Henri

**Comment by ItsTheJetstream** [comment]
@mischa67 I do not have such an LED strip but this question was asked a number of times before. Check out #123. A user there found a way of adapting this code for these lights. you might give it a shot.

**Comment by joeybab3** [comment]
Also a duplicate of #47, it's since been solved.
