### ISSUE TITLE
import _portaudio error

### ISSUE THREAD

**Issue by jaydee7** [scottlawsonbc/audio-reactive-led-strip#137]
Hello
I have followed all of the readme instructions but when i try to run visualization.py in anaconda i get,
        (import _portaudio as pa
ModuleNotFoundError: No module named '_portaudio')
I am still in the process of leaning python but have not been able to find anywhere of how to fix this issue. Any advice would be much appreciated!

Also when i run visualization.py in spyder it works just fine.

**Comment by arvid888** [comment]
Try to download portaudio using anaconda navigator.

Environments --- visualization-env --- search --- portaudio

be sure to check "all" in the drop-down next to search

**Comment by jaydee7** [comment]
In the anaconda navigator it says i already have portaudio v19.6.0 installed in my environment but I am still getting the same error.

(visualization2-env) C:\Users\John>C:\Users\John\Desktop\visualization.py
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "C:\Users\John\Desktop\visualization.py", line 7, in <module>
    import microphone
  File "C:\Users\John\Desktop\microphone.py", line 3, in <module>
    import pyaudio
  File "C:\Users\John\Desktop\pyaudio.py", line 116, in <module>
    import _portaudio as pa
ModuleNotFoundError: No module named '_portaudio'

**Comment by Fercho120** [comment]
Same error on a different program, in my case occurs when I try to import pyaudio (which requires portaudio)

**Comment by toshug** [comment]
i am facing the same problem

**Comment by PRO2XY** [comment]
I got over this issue by:
1. Using python 2.7 (not sure if this was required)
2. Deleting pyaudio and portaudio from conda, and installing pyaudio using pip. 

It works now.

**Comment by Viraj-creation312** [comment]
If you facing same problem then
Simply do 
Pip unistall pyaudio
Pipwin install pyaudio
For windows machine

**Comment by Harshchourasiya** [comment]
> If you facing same problem then Simply do Pip unistall pyaudio Pipwin install pyaudio For windows machine

This is working Thanks
