### ISSUE TITLE
Using arduino instead of esp8266

### ISSUE THREAD

**Issue by portalgamesmais** [scottlawsonbc/audio-reactive-led-strip#145]
Is it possible to use an arduino Board(Leonardo or mega) over usb instead of an esp8266?

**Comment by i130233** [comment]
First of all wifi board is must for this 
Secondly, check whether I2S is available in Arduino

**Comment by joeybab3** [comment]
You would need to implement using serial instead of wifi, this has been requested before and I might look into it.
