### ISSUE TITLE
Any ways to modify the centre point?

### ISSUE THREAD

**Issue by surajkhan** [scottlawsonbc/audio-reactive-led-strip#146]
Is it possible to change the pount of origin in scroll effect or all the effects? In the current scenario, all the points origin from the central point of the strip. Is it possible to modify it? I am already going through your python code, but a little heads up where to tinker woud be very much helpful. :)

**Comment by rando-calrissian** [comment]
You can do an np.roll of the desired amount right before you output it to the strip.  So you could add a parameter to config.py called N_PIXEL_OFFSET 32 (or whatever) and then in led.py for the appropriate device add :

```
        if config.N_PIXEL_OFFSETis not 0:
          pixels = np.roll( pixels, config.N_PIXEL_OFFSET, axis=1)
```

**Comment by surajkhan** [comment]
Thanks ! and I eventually figured this part out :)
