### ISSUE TITLE
i get connection between virtualiser and esp8266 (nodemcu) buth no animation

### ISSUE THREAD

**Issue by Nappen** [scottlawsonbc/audio-reactive-led-strip#147]
So i have managed to get the fps count to transfer so the esp8266 registrer that it recives data from computer. buth no animation. the data pin is connected to rx1 any idé what the problem can be?

**Comment by not-matt** [comment]
Is your strip properly powered?

**Comment by Nappen** [comment]
i  run a 5v 10amp brick and the led lights work with ws2812fx so yeah they are powered =)

**Comment by surajkhan** [comment]
are your led length in the esp8266 firmware, i.e in the ino fine and in the config.py file the same?

Check that, the number of pixels should be same. 

I hope this might help cheers!

**Comment by Nappen** [comment]
yeah i put 150 in both as i have 144 leds on the strip

**Comment by surajkhan** [comment]
put 144 both in the ino and python file

**Comment by Nappen** [comment]
did not do any diffrence. start to wounder if my nodemcu has wired rx connector. because it seams like i dont get signal at all.

**Comment by surajkhan** [comment]
what did u put as the pin number in ino file

**Comment by Nappen** [comment]
eh dont have anywere to put a dedicated pin in the .ino file

**Comment by Kronoskrk** [comment]
where did you find it?
