### ISSUE TITLE
nodeMCU does not output to the strip

### ISSUE THREAD

**Issue by schnellecom** [scottlawsonbc/audio-reactive-led-strip#148]
Hi,
I set up the nodeMCU and python with anaconda on my PC. When I start the visualization.py it shows me an animation and the serial monitor tells me that it receives around 60FPS.

But the Strip does just stay white. When I restart it does not even turn on. 

The Strip is connected to the RX port as described

**Comment by Kronoskrk** [comment]
same issue, could you solve it?

**Comment by RecLeKon** [comment]
same problem here. found an fix?

**Comment by ZZKdev** [comment]
> 
> 
> same problem here. found an fix?

same issue, could you solve it?

**Comment by RecLeKon** [comment]
I switched  to an other fork of this project https://github.com/not-matt/Systematic-LEDs works better than the original. he made a nice tutorial about it to. it also has way more features

**Comment by not-matt** [comment]
Glad you like it!
