### ISSUE TITLE
[Feature request] Add OTA support

### ISSUE THREAD

**Issue by Atraii** [scottlawsonbc/audio-reactive-led-strip#15]
New versions of the ESP8266 arduino firmware have ArduinoOTA support. This allows flashing over WiFi, and removes the need to plug in the ESP8266 into a computer each time for upgrades. 

This feature may be a security risk but would be useful for testing. Ideally it would be disabled/enabled at user request.

**Comment by joeybab3** [comment]
I'll consider working on this is Scott wants to merge it but at the moment I think we are working on the following things:
Wifimanager
Replacing the current ws2812 library
(More leds?)

**Comment by Atraii** [comment]
My current ESP  codebase uses the very high quality [ESPManager](https://github.com/sticilface/ESPmanager), which allows for automatic connections, static IP on recognized connection, setting device name, connecting to device directly when no known connection is available and more. I'd give it a look. I can also post my own code as a reference. (I currently have packets indexed and with an action command so it is a bit different, but the information is read directly from the buffer to the pixels)

**Comment by scottlawsonbc** [comment]
Is there a consensus as to which of ESPManager and WiFiManger is better? I'd like to incorporate one of these into the codebase, I know @joeybab3 has a working version of the WiFiManager code, but I can't remember if I was able to get static IP addresses working on that code.

**Comment by joeybab3** [comment]
I personally haven't used ESPManager, but if Atraii feels it's better, I'm more than happy to write up another sketch. I can also check OTA with either later. Both appear to support static IP configurations, with the wifimanager just having to add the line `wifiManager.setSTAStaticIPConfig(IPAddress(192,168,0,99), IPAddress(192,168,0,1), IPAddress(255,255,255,0));`

**Comment by schnellecom** [comment]
This is a kinda old request but I would also be interested in OTA support

**Comment by joeybab3** [comment]
> This is a kinda old request but I would also be interested in OTA support

I can help you write up a version with OTA support if you'd like?
