### ISSUE TITLE
Leds Defaulting on, Raspberry Pi 3 set up

### ISSUE THREAD

**Issue by hultbrod** [scottlawsonbc/audio-reactive-led-strip#155]
I have everything up and running, and visualization.py seems to be working fine, but the lights default to being on. Is there anyway to fix this? I am running a 5 meter strip of 150 leds, with a 5V 10A power source. It is wired according to this guide [https://dordnung.de/raspberrypi-ledstrip/ws2812](url) . I have been looking through visualization.py and python.py but have not been able to figure it out. Thanks.

**Comment by not-matt** [comment]
Change audio input to stereo mix through control panel. What you're likely
seeing is noise from the microphone when no music is playing.

**Comment by hultbrod** [comment]
Will try it and get back to you, having to set it up again as the sd card corrupted. Thanks for the quick response!

**Comment by hultbrod** [comment]
Problem wasn't there after redoing it, if I had to guess I think I may have left the logic inverter in config.py set to True instead of False. Thanks for the all the help, some of your other replies to issues helped me elsewhere.
