### ISSUE TITLE
GUI does not work properly

### ISSUE THREAD

**Issue by Coder427** [scottlawsonbc/audio-reactive-led-strip#156]
Everything works except the GUI. How can I fix it?

![test](https://user-images.githubusercontent.com/39198237/41511053-e7bd83f6-726f-11e8-81f9-fec0f2f73285.PNG)

**Comment by joeybab3** [comment]
What python version are you using?

**Comment by Coder427** [comment]
I am using Python 2.7.13 on Windows 7.
