### ISSUE TITLE
Low amount of Red in the 'Spectrum' Visualization"

### ISSUE THREAD

**Issue by Bretley** [scottlawsonbc/audio-reactive-led-strip#164]
I've noticed that there isn't much red in the LED 'Spectrum' visualisation. There is plenty in the scroll and energy effects, with lovely deep reds and light pinks. However spectrum does not seem to show much depth in red. The red also seems to be sufficiently present in the gui visualisation too

About my  setup:
I'm running this as if there were an esp8266 at the other end, but it's just a RPI receiving the signal and coloring the pixels. I have tried with gamma correction on and off. Is this more to the nature of the spectrum visualization (lots of overlap= white) or is there some slight color shifting I ought to do to due to the rpi?

Other than that, this is amazing and pretty much exactly what I wanted. Thank you for your time

**Comment by bugilt** [comment]
Not=Matt's fork has a few more options. I'm still trying to run it on a standalone pi with no luck. Scott's version runs great on my standalone pi3b setup. I'm getting 30+fps running 300 leds. 

https://www.youtube.com/watch?v=W4jaAgjfvG8
https://github.com/not-matt/audio-reactive-led-strip
