### ISSUE TITLE
In nodemcu, it only transmits data when the data line is disconnected.

### ISSUE THREAD

**Issue by ZZKdev** [scottlawsonbc/audio-reactive-led-strip#167]
I can be sure it has the data transferred to the esp8266

**Comment by joeybab3** [comment]
What is "it" in this case? Are you meaning the computer can only upload if the data line is disconnected, or that the pc only transmits the visualizer frames when it's connected? Also what is the data line?

**Comment by ZZKdev** [comment]
> What is "it" in this case? Are you meaning the computer can only upload if the data line is disconnected, or that the pc only transmits the visualizer frames when it's connected? Also what is the data line?

I used the neopixel based fork and it worked. As far the above error is concerned I have to use the GitHub version of the esp8266 library. Weird but that did the trick...

https://github.com/joeybab3/audio-reactive-led-strip/blob/master/arduino/ws2812_controller/ws2812_controller.ino
