### ISSUE TITLE
Issue with 30 leds/meter

### ISSUE THREAD

**Issue by ilabarge** [scottlawsonbc/audio-reactive-led-strip#169]
Has anyone had trouble with getting this to work with 30 leds/meter with the ESP8266? It works fine with 60 leds/meter. 

Setup:
-Windows 10
-Voicemeeter
-NodeMCU v3
-Tried both [Alitov](https://www.amazon.com/ALITOVE-WS2812B-Individually-Addressable-Waterproof/dp/B00ZHB9M6A/ref=sr_1_3?ie=UTF8&qid=1539995446&sr=8-3&keywords=alitove+ws2812b) and adafruit [neopixel](https://www.adafruit.com/product/1376?length=1)

**Comment by joeybab3** [comment]
What sort of trouble are you experiencing, like it just doesnt light the LEDs?

**Comment by ilabarge** [comment]
After testing on several different strips, what I'm seeing is that the WS2812B strips purchased recently (within a year) are not working with either the visualizer application or the led.py test application. 

The older strips, purchased ~2 years ago work great with both the visualizer and test application. It seems to be a change in the WS2812B at some point. Has anyone else experienced problems using the ESP8266 and new WS2812B strips with these programs?

**Comment by joeybab3** [comment]
Some strips use different but orders(like GRB instead of RGB) I don’t remember if the main branch supports changing that by the neopixel bus PR I have does

**Comment by cdurth** [comment]
@ilabarge i had some better luck with @joeybab3's fork https://github.com/joeybab3/audio-reactive-led-strip
This uses a different LED driver, im not getting the clean filtered results like the demo GIF's, but this can probably be cleaned up with the python code instead of troubleshooting the LED driver.

**Comment by ilabarge** [comment]
@cdurth @joeybab3's firmware update exactly worked. Thanks for that! I should have guessed it was a problem with the driver. With my setup, the results are pretty close to the demo, good color space, consistency etc.

**Comment by cdurth** [comment]
@joeybab3 the issue i am having, is the LED strip never appears to go black, even when no data is being sent, it appears to hold the last state, however, the LEDs will flicker to frequency changes/data being sent from the visualization. When no data is being sent (logging the packet in python & on the esp), the strip will flicker like crazy, producing a white/blue strobe

Any ideas?

I thought i could perhaps 'trick' the strip to turn off when the packetSize is null, but this results in a quick flicker to black, then looks to be cycling RGB. I also hardcoded the RGB in led.py to orange only, and im still getting flickers of solid R/G/B.

Im going to see if i have anothe ESP board around and see if there is something funky with this one, maybe im getting some odd noise from the RX pin, idk.

**Comment by joeybab3** [comment]
Something you said, specifically the “holds the last state” reminds me of my strip when I used it on a crappy WiFi router... I can’t quite figure out what causes it but it does seem to go away when I switch esp’s. It will hold a patch of the strip one color until it gets relit up by another beat or scroll.  I’m going to look into this when I’m not in the passenger seat in heavy traffic :P

**Comment by joeybab3** [comment]
I've since merged my fork onto the master so I'll close this issue.
