### ISSUE TITLE
Error in running visualization.py

### ISSUE THREAD

**Issue by bogartescobar** [scottlawsonbc/audio-reactive-led-strip#170]
when I run visualization.py I get this error:
`Traceback (most recent call last):
  File "visualization.py", line 257, in <module>
    import pyqtgraph as pg
  File "/usr/local/lib/python2.7/dist-packages/pyqtgraph/__init__.py", line 13, in <module>
    from .Qt import QtGui
  File "/usr/local/lib/python2.7/dist-packages/pyqtgraph/Qt.py", line 44, in <module>
    raise Exception("PyQtGraph requires one of PyQt4, PyQt5 or PySide; none of these packages could be imported.")
Exception: PyQtGraph requires one of PyQt4, PyQt5 or PySide; none of these packages could be imported.
`

**Comment by not-matt** [comment]
More often than not, the error gives you a good idea of the solution. At
the end of the error, it reads "PyQtGraph requires one of PyQt4, PyQt5 or
PySide; none of these packages could be imported."

The program couldn't find the PyQt5 module. Have you installed it?

**Comment by Lord-FEAR** [comment]
There was a similar problem. installing pyqt5 solved it.
`python -m pip install pyqt5`

**Comment by bogartescobar** [comment]
I seem can't install pyqt5... Raspian throws an error:

`Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5
`

**Comment by bogartescobar** [comment]
rasbian throws this error when running `pip install pyqt5`:
`Could not find a version that satisfies the requirement pyqt5 (from versions: ) No matching distribution found for pyqt5`

**Comment by joeybab3** [comment]
Have you tried python 3.5?

**Comment by ajzeller** [comment]
I am using macOS and getting the same error with Python 3.7. I have installed PyQt5 with `pip3 install pyqt5`. I wonder if it is not looking for PyQt5 in the right location...

What python version are people having success with?

**Comment by richyxi** [comment]
U can use conda

**Comment by Rworld-Ravi** [comment]
Hi. I had the same situation on windows , pyqt5 and pyqt4 weren't installing, but installing pyside , `pip install pyside` , did solve issue for me.

**Comment by FerdinandFidel** [comment]
To use python3 solved the problem for me.
