### ISSUE TITLE
Internal audio visualization?

### ISSUE THREAD

**Issue by bogartescobar** [scottlawsonbc/audio-reactive-led-strip#173]
Is that possible? If so, how?

**Comment by joeybab3** [comment]
What do you mean by "internal audio visualization"? Are you meaning using the computers audio output as the source for the visualization?

**Comment by bogartescobar** [comment]
@joeybab3 yes...

**Comment by joeybab3** [comment]
It is also possible if you use the "stereo mixer" device that I've found on some Windows devices.

**Comment by Andriejus** [comment]
And how to do it on MacOS?

**Comment by Andriejus** [comment]
Thank you. I watched this tutorial and it was helpful, because Im using macOS high siera
https://www.youtube.com/watch?v=kxx0gNyfXV8
