### ISSUE TITLE
Esp 8266 over usb

### ISSUE THREAD

**Issue by Kronoskrk** [scottlawsonbc/audio-reactive-led-strip#176]
Hi,
very cool project and everything is working fine. But I like to make a second build without the need of a wireless connection (WLAN). Is there a easy way to do this, so that I only have to connect the ESP over USB to my Laptop (with python and co.)?

**Comment by joeybab3** [comment]
I could probably do the Arduino side of it, but python is not my best language so I would need some help getting that working but it should be possible.

**Comment by scottlawsonbc** [comment]
The ESP8266 could, at least in theory, use the virtual serial port to communicate with the host PC. This isn't supported by this project, but I would consider a pull request if you made this work. The baud rate would likely need to be fairly high in order to make this work.
