### ISSUE TITLE
Asus TinkerBoard

### ISSUE THREAD

**Issue by RFS96** [scottlawsonbc/audio-reactive-led-strip#184]
Hi,

I`ve tried running the code and I get:

Traceback (most recent call last):
  File "/home/linaro/rpi_ws281x/python/examples/strandtest.py", line 91, in <module>
    strip.begin()
  File "build/bdist.linux-armv7l/egg/neopixel.py", line 106, in begin
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)

Any idea on how to solve this? I suppose it does some check of the HW.

**Comment by scottlawsonbc** [comment]
You are running this on an Asus TinkerBoard? It would seem that the neopixel library is not compatible with the Asus TinkerBoard which would explain why it throws the hardware revision exception.
