### ISSUE TITLE
Raspberry pi 3 crashes and shuts down...

### ISSUE THREAD

**Issue by bogartescobar** [scottlawsonbc/audio-reactive-led-strip#188]
when I run visualization.py , my Pi just closes all it's connectivity. My VNC and SSH connections were closed but the Pi is still connected to my Wifi network. What  would be the solution?

**Comment by joeybab3** [comment]
Any errors printed when this happens?

**Comment by richyxi** [comment]
same to me, it print something about a audio buffer has overflowed, its a problem with my audio set up?

**Comment by joeybab3** [comment]
Is either of you able to post some of the output to help us debug the issue?

**Comment by parzival156** [comment]
I have a similar issue. After running visualization.py my pi freezes on my vnc. Here is an image from my vnc of what came up on the terminal after I ran it. 

You'll notice the message top-right saying my micro-sd card was ejected, is this something to raise concern over, or is this a normal thing to happen when a pi freezes?

![error](https://user-images.githubusercontent.com/54527699/63673626-91b51c00-c799-11e9-829f-5c4e547cb2ba.PNG)
