### ISSUE TITLE
Adafruit_NeoPixel not an attribute to neopixel??

### ISSUE THREAD

**Issue by ghost** [scottlawsonbc/audio-reactive-led-strip#190]
File "/home/pi/Desktop/audio-reactive-led-strip-master/python/led.py", line 15, in <module>
    strip = neopixel.Adafruit_NeoPixel(config.N_PIXELS, config.LED_PIN,
AttributeError: module 'neopixel' has no attribute 'Adafruit_NeoPixel'

**Comment by joeybab3** [comment]
Which version of the adafruit library do you have installed on your Rpi?

**Comment by TimStavrakos** [comment]
I have the same issue using version 3.3.5 of adafruit-circuitpython-neopixel

**Comment by ogilvieliam** [comment]
Same issue with adafruit-circuitpython-neopixel 6.0.0, do I need to downgrade? If so, to which version?
