### ISSUE TITLE
Audio on RPI

### ISSUE THREAD

**Issue by richyxi** [scottlawsonbc/audio-reactive-led-strip#194]
what do i need to play music in the visualizer and also in the speakers?

**Comment by joeybab3** [comment]
A microphone

**Comment by richyxi** [comment]
I have already a USB audio device but Idk the connections between the music player, RPI and the speakers, can you help me with this?

**Comment by joeybab3** [comment]
You should be able to play music out of speakers, and just have a microphone listen to that

**Comment by richyxi** [comment]
Okay, thxs for the info!

**Comment by joeybab3** [comment]
No problem
