### ISSUE TITLE
Sending music input via bluetooth?

### ISSUE THREAD

**Issue by vayeetya** [scottlawsonbc/audio-reactive-led-strip#197]
Wanted to know if I could just connect my phone to the pi via bluetooth and play receive music input that way. Sorry, this really isn't an issue but I really wanted to know.

**Comment by joeybab3** [comment]
It would require probably a separate app, I’m not sure if the pi is able to connect to a phone as a2dp/whatever the audio device profile is though?

**Comment by richyxi** [comment]
https://didier.io/post/raspberrypi-stream-sound-over-bluetooth

**Comment by richyxi** [comment]
This may help

**Comment by vayeetya** [comment]
Thanks for the input guys, really appreciate it. I am able to play music through my phone (which is connected to the pi via bluetooth) and hear it on the speakers (which is also connected to the pi). Now I just have to find a way to process that signal :)

**Comment by richyxi** [comment]
Check your input devices by running this script https://gist.github.com/richyxi/2489072901c0e9e6f370cbfa3b9539e0

**Comment by richyxi** [comment]
And make the Bluetooth audio input your default
