### ISSUE TITLE
visualize_scroll displays errors, visualize_energy doesn't display

### ISSUE THREAD

**Issue by joeybab3** [scottlawsonbc/audio-reactive-led-strip#2]
When running the scroll function, I end up with the error: 
`TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'`
Specifically it doesn't like line 132 in visualize.py:
`p *= 0.98`

As for `visualize_energy`, I can't get that one to display anything, but it doesn't give any errors.

I'm running anaconda on windows 8, and I copied and pasted the pip installs/conda installs as recommended.

**Comment by scottlawsonbc** [comment]
I'm away from my computer for a few hours but I'll look into this as soon as I can. Are you able to get any of the effects working? Does the spectrum effect work?

**Comment by joeybab3** [comment]
Yes spectrum and max work

**Comment by scottlawsonbc** [comment]
Not a problem at all! I'm just excited to see that people that are using the project.

I think I might know the issue. In visualization.py, can you try changing the line:

`p = np.tile(1, (3, config.N_PIXELS // 2))`

To

`p = np.tile(1.0, (3, config.N_PIXELS // 2))`

Can you let me know if that works? This should change `dtype` from `int32` to `float64` and hopefully resolve the issue. I apologise for the inconvenience.

**Comment by scottlawsonbc** [comment]
Hmm.. alright I will need to look into this when I get back to my computer in about an hour.

**Comment by scottlawsonbc** [comment]
Thank you again for bringing this issue to my attention. I can reproduce the problem and I have identified the root cause. I wrote the code in Python 2.7 but made a couple of small errors when making it compatible with Python 3.5. I am working on a fix and will have it available shortly.

**Comment by scottlawsonbc** [comment]
Commit e874ed3 should fix this. Could you please confirm whether this issue is resolved?

**Comment by joeybab3** [comment]
Theyre all working again! Thanks!

**Comment by scottlawsonbc** [comment]
Awesome! Sorry for any inconvenience this issue has caused.
