### ISSUE TITLE
Network MTU limits pixel count

### ISSUE THREAD

**Issue by Atraii** [scottlawsonbc/audio-reactive-led-strip#20]
I have noticed that I can't go above 417 pixels on my regular home network even modifying the experimental branch to suit. I believe I have determined the issue to be the Maximum Transmit Unit (MTU) on my network. Even increasing `BUFFER_LEN = 1024` to `BUFFER_LEN = 4096` has no effect. Wireshark confirms that the python code is sending the correct packets, but nothing is receiving them.

As it is not very common to be sending packets this large, it might be necessary to incorporate a fragmentation routine to break up packets into something reasonable.

**Comment by scottlawsonbc** [comment]
You're right, this is a good point. The maximum "safe" UDP packet size is 576 bytes, which allocates 508 bytes for data, 60 bytes for the IP header, and 8 bytes for the UDP header.

I'll change the code to send multiple packets, with each packet being no larger than the maximum safe size. This will require a change in the communication protocol and a reflash of firmware.
