### ISSUE TITLE
Can this project run without PC, just arduino or raspberry pi zero?

### ISSUE THREAD

**Issue by Treedye** [scottlawsonbc/audio-reactive-led-strip#203]
I was thinking about some low-cost controller to run this awesome animations. Can Raspberry Pi Zero handle them on like stable 30-40 FPS with getting and analyzing the song input itself? Or maybe some arduino controllers?

**Comment by decapeter2** [comment]
it can run on rasp pi 2 or 3 so it could run also on pi zero, you just need to use GPIO 18. But i dont know if the pi zero if fast enougth to calculate the effets... must try !

**Comment by joeybab3** [comment]
I don't have anything to test it on, but other than rPi we don't currently support any standalone solutions.
