### ISSUE TITLE
Burned the one and only pwm, 18th pin on raspberry pi...

### ISSUE THREAD

**Issue by Treedye** [scottlawsonbc/audio-reactive-led-strip#204]
Burned the pwm pin on raspberry pi. Now I use 13th pin to connect to the led. The FPS dropped from ~60 to ~13, and there are some weird flickering that randomly occurs. e.g. half of the leds turn into random colors for like 1/10 of a second. The connection seems to be fine.

Is there any way to get the FPS higher, and to get rid of the flickering? I heard that raspberry pi can simulate the pwm somehow on any pin. Any ideas?

**Comment by lpearl** [comment]
I have been using pin 21 with no problems just make sure it's grounded and power is injected where appropriate.
