### ISSUE TITLE
Rearrange LED order 

### ISSUE THREAD

**Issue by mayor-slash** [scottlawsonbc/audio-reactive-led-strip#207]
Hi ,
First of all thanks for your great work!!
The system is allready running and I am having the time of my life looking at the animations. 
I have build in the LED stripe into my infinity mirror table and it looks awsome. 

The only problem I am facing is that the origin of the animation is not the middle of the table. This is due to bad wiring on my part. The "first" Led is neither in a corner nor in the middle of one side. Is it possible to rearrage the LEDs in the code? 
I am currently running 204 LEDs and my goal is that the thirty-second becomes the first LED so that the animation is symmetrical on the table. 

I hope its not to much of a problem and it would be great if someone could help me. 
Thanks!

**Comment by joeybab3** [comment]
So you are looking to have only the first 64 LEDs utilized or are you saying that led 32 is the middle of the table and goes 102 leds around either side but wraps around to the end?

If so you can probably edit the arduino code with a simple subtraction and then if loop.
