### ISSUE TITLE
A few questions - Visualizer headless? 

### ISSUE THREAD

**Issue by microfx** [scottlawsonbc/audio-reactive-led-strip#208]
Hey!

First I'd like to note that on the Raspberry Pi Pin 18 and GPIO18 are differently - Pin 18 is GPIO5 - maybe this could be better described as it took me a while to figure this out. 

Now my question: Do I have to use the GUI (once / always)? I am running a headless Rpi 3 setup and don't have a monitor for it.

Thanks for this superb guide/code otherwise. Maybe another hint: The structure of your tutorial is a bit weird - I followed the wrong path and tried to install everything with "pip install" where I ran into looots of trouble because nothing was compiling successfully - until I read a little further and saw that there is a guide with apt-get. Maybe hint a littler earlier that there is a dedicated Raspberry installation guide. Took me a while as well ;) Also you forgot to mention that one maaaybe need your repository to run your code - it is missing in your writeup as well - though this didn't take too long for me to grasp - but you might add that.

I am now trying to figure out how to route audio back to your application.

**Comment by joeybab3** [comment]
You do not need to run the GUI, and in fact, it's even recommended to disable it on the readme. I have added the GPIO pin to it and as for the other changes, I'll go over it in depth when I get the time and see if there are any improvements to be made.
