### ISSUE TITLE
 problem with mopidy and your code.

### ISSUE THREAD

**Issue by Firemanpl** [scottlawsonbc/audio-reactive-led-strip#209]
I have raspberry pi zero and I want to install mopid on it and control music through MPD droid apps. And I have a question because mopidy sends music to the sound card right away.I would like your code to receive a signal from the headphone output and not from the microphone input. Can I do that?

**Comment by richyxi** [comment]
i think you have to route the audio from input to output by modify the mopidy source code, you can ask maybe in their forums. otherwise by looking into the pyaudio library, maybe theres another way to stream the audio from an output source
