### ISSUE TITLE
using audio output as input for visualization on mac

### ISSUE THREAD

**Issue by peanutboy** [scottlawsonbc/audio-reactive-led-strip#212]
Hello! 
First of all thank you for the great work. Has anyone of the mac users found a way to playback the audiooutput into the visualization programm? I dont really understand how it should work with loopback.

Greetings!

**Comment by joeybab3** [comment]
Check out Scott's reply on https://github.com/scottlawsonbc/audio-reactive-led-strip/issues/10#issuecomment-271173120

Let me know if any of the programs mentioned work for you.
