### ISSUE TITLE
Arduino compiling error in Neopixelbus

### ISSUE THREAD

**Issue by sladaar** [scottlawsonbc/audio-reactive-led-strip#214]
Hey all, sorry to bother but i can't figure out why i have these errors (arduino ide 1.8.9, on nodemcu 1.0).
Libraries and boards are up-to-date.

I hope someone can point me what to check!

Thanks a lot in advance!

`In file included from C:\Users\Ed-ssd\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:67:0,
from C:\Users\Ed-ssd\Documents\Arduino\audio-reactive-led-strip-master\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266.ino:5:`

`C:\Users\Ed-ssd\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/NeoEsp8266DmaMethod.h:335:58: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
volatile static void ICACHE_RAM_ATTR i2s_slc_isr(void)
`
`C:\Users\Ed-ssd\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/NeoEsp8266DmaMethod.h: In instantiation of 'NeoEsp8266DmaMethodBase<T_SPEED>::NeoEsp8266DmaMethodBase(uint8_t, uint16_t, size_t) [with T_SPEED = NeoEsp8266DmaSpeedWs2812x; uint8_t = unsigned char; uint16_t = short unsigned int; size_t = unsigned int]':`

`C:\Users\Ed-ssd\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:106:61:   required from 'NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::NeoPixelBus(uint16_t, uint8_t) [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x>; uint16_t = short unsigned int; uint8_t = unsigned char]'`

`C:\Users\Ed-ssd\Documents\Arduino\audio-reactive-led-strip-master\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266.ino:24:73:   required from here`

`C:\Users\Ed-ssd\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/NeoEsp8266DmaMethod.h:142:5: warning: unused parameter 'pin' [-Wunused-parameter])`

`NeoEsp8266DmaMethodBase(uint8_t pin, uint16_t pixelCount, size_t elementSize) : NeoEsp8266DmaMethodBase(pixelCount, elementSize)`

Btw, i can upload anyway, i'll check and post if it works

**Comment by sladaar** [comment]
update: it does work properly, or at least it seems (tweaks and imprecise sensitivity maybe aren't due to the compile), so i don't know what these errors involves.

**Comment by joeybab3** [comment]
That sounds like an issue with the neopixepbus library. I’ll compile and see if I can reproduce and if so I can file it in their repo.

**Comment by joeybab3** [comment]
I couldn't reproduce this, let me know if this is still an issue and I can try and help troubleshoot it further.

**Comment by sladaar** [comment]
thanks @joeybab3 , but i use another code for the hardware side now (Wled), with E1.31 protocol.
