### ISSUE TITLE
Spectrum single color

### ISSUE THREAD

**Issue by JustinL-12** [scottlawsonbc/audio-reactive-led-strip#216]
The spectrum mode seems to only show a light purple color. I was wondering if there was a better version of it out there. Also, would there be a way to make the colors across the strip a rainbow (like in rpi_ws281x strandtest.py), but just have the brightness set by the music frequencies? Thanks!

**Comment by joeybab3** [comment]
As of now, wysiwyg, but we are working on a lot of improvements for both performance and visual appeal.

**Comment by NickSutton** [comment]
Was looking in to this, spectrum is my fav, but would be interested to see other colour combos
