### ISSUE TITLE
ESP not receiving data from PC

### ISSUE THREAD

**Issue by Erdem2706** [scottlawsonbc/audio-reactive-led-strip#221]
![Screenshot (16)](https://user-images.githubusercontent.com/53051677/61468127-1338b380-a97d-11e9-8b3e-519d6fe30a31.png)

**Comment by Erdem2706** [comment]
My Pc dont send the FPS to the esp pls help

**Comment by joeybab3** [comment]
Do the IP addresses of both the config and the actual esp device match?

**Comment by Erdem2706** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/53051677/61472161-2c912e00-a984-11e9-9e88-6ab96ba77508.png)

yes

**Comment by Erdem2706** [comment]
already fixed it. as you said the esp just took another ip. so i changed it in the config and the esp data to the ip which showed up in the serial monitor and it worked.

**Comment by Erdem2706** [comment]
Thank you anyway for your help

**Comment by joeybab3** [comment]
No Worries
