### ISSUE TITLE
PI 4? 

### ISSUE THREAD

**Issue by bugilt** [scottlawsonbc/audio-reactive-led-strip#222]
I haven't heard of any mention of if this would work on a pi 4 or is it to early. I didn't see anything posted about it so thought I'd give it a go.

**Comment by joeybab3** [comment]
In theory, it should work, I don't have one to try it on but feel free to give it a shot and if you do report back here!

**Comment by greggiusclay** [comment]
How did you go with pi 4 @bugilt? 
In theory can we expect better performance on pi 4 with more fps?  Any chance it would be able to run gui window at same time as visualisations?

**Comment by bugilt** [comment]
I can't seem to find my usb audio. I've ordered a new one. should be here tomorrow.

**Comment by bugilt** [comment]
I'm getting average 41 fps with desktop and gui running over remote desktop.

**Comment by richyxi** [comment]
How u can run it remotely? Im trying to archive that with no success

**Comment by bugilt** [comment]
I'm running it with VNC.

**Comment by joeybab3** [comment]
Seems like this is possible to run on the pi 4 so I will close this issue. Reopen if there is something else you would like to address.
