### ISSUE TITLE
error code on windows

### ISSUE THREAD

**Issue by nikhilprojects101** [scottlawsonbc/audio-reactive-led-strip#223]
![Screenshot (1)_LI](https://user-images.githubusercontent.com/53110322/61731144-76b94b80-ad98-11e9-8cce-174ab1b9b947.jpg)
 
Getting error even after installing everything

**Comment by joeybab3** [comment]
did you run pip install pyaudio within the env?

**Comment by joeybab3** [comment]
Reading further I can see that you did, did you install it outside of the env as well?

**Comment by nikhilprojects101** [comment]
yes

**Comment by nikhilprojects101** [comment]
what should i do.? I am not able to do the led visualizer project!

**Comment by joeybab3** [comment]
What version of windows are you on, and what version of python?

**Comment by nikhilprojects101** [comment]
windows 10. and python 3.7.3

**Comment by andreseichi** [comment]
Having the same issue. Installed all packages and dependencies, but getting error with the python programs, same windows 10 and python 3.7.3. Installed pyaudio after a lot of trouble.

**Comment by MackRhine** [comment]
I am also having the same problem. I've installed pyaudio on both the virtual environment and python 3.5.4. windows 10.

**Comment by joeybab3** [comment]
@nikhilprojects101 @andreseichi @MackRhine Could one of you try running pip3 install pyaudio in both the env and outside of it to see if installing the python3 version fixes it?

**Comment by MackRhine** [comment]
Howdy, 

I tried that, it said the requirements were already satisfied both times. I figured that everything should work, but I ran into a new error. apparently pyqtgraph requires PyQt4, PyQt5, or PySide, and none of these can be imported. I'll post the full error code in a new issue.

**Comment by inange** [comment]
@nikhilprojects101 
here is the solution 
`pip uninstall pyaudio`
and then 
`pip3 install pyaudio`

**Comment by joeybab3** [comment]
@nikhilprojects101 Are you still experiencing this issue/still attempting to solve it? If not I'll mark this as finished.

**Comment by nikhilmahanta5** [comment]
isuue solved

**Comment by manyaOnIsle** [comment]
I tried to use the above command  and i am using conda environment.
I get following  error
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/


full message 
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\thoma\\AppData\\Local\\Temp\\pip-install-s5atxe3n\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\thoma\\AppData\\Local\\Temp\\pip-install-s5atxe3n\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\thoma\AppData\Local\Temp\pip-wheel-akazq0r0'
       cwd: C:\Users\thoma\AppData\Local\Temp\pip-install-s5atxe3n\pyaudio\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying src\pyaudio.py -> build\lib.win-amd64-3.8
  running build_ext
  building '_portaudio' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\thoma\\AppData\\Local\\Temp\\pip-install-s5atxe3n\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\thoma\\AppData\\Local\\Temp\\pip-install-s5atxe3n\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\thoma\AppData\Local\Temp\pip-record-6wc5cssp\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\pyaudio'
         cwd: C:\Users\thoma\AppData\Local\Temp\pip-install-s5atxe3n\pyaudio\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying src\pyaudio.py -> build\lib.win-amd64-3.8
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\thoma\\AppData\\Local\\Temp\\pip-install-s5atxe3n\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\thoma\\AppData\\Local\\Temp\\pip-install-s5atxe3n\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\thoma\AppData\Local\Temp\pip-record-6wc5cssp\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\pyaudio' Check the logs for full command output.

**Comment by joeybab3** [comment]
@manyaOnIsle Install visual studio build tools. If you are having trouble doing this feel free to open a new issue.

**Comment by manyaOnIsle** [comment]
> @manyaOnIsle Install visual studio build tools. If you are having trouble doing this feel free to open a new issue.

@joeybab3 - Thanks will do this.
