### ISSUE TITLE
Can’t find visualization.py to run it

### ISSUE THREAD

**Issue by schrotbe2021** [scottlawsonbc/audio-reactive-led-strip#224]
I’m using Raspbian Lite and i was able to run setup.py and strandtest.py but I can’t find visualization.py

**Comment by joeybab3** [comment]
Did you download the whole thing from github/clone it? it should be in the same directory as the others.

**Comment by bugilt** [comment]
The directions for pi skip the step of downloading the project.

**Comment by joeybab3** [comment]
Ok, I added an instruction that says you have to download the code before running it.

**Comment by schrotbe2021** [comment]
> Did you download the whole thing from github/clone it? it should be in the same directory as the others.

Now I feel dumb! haha thank you very much!

**Comment by himynameisulpa** [comment]
Why is this issue still open?

**Comment by joeybab3** [comment]
@himynameisulpa I leave issues open for followup questions sometimes and as you can probably tell I haven't been able to put much time into this repo so since OP didn't close it I haven't either but I will close it now...
