### ISSUE TITLE
Low voltage and not all LED's are reacting

### ISSUE THREAD

**Issue by schrotbe2021** [scottlawsonbc/audio-reactive-led-strip#225]
I am getting a low voltage warning and also only a small number are reacting to the LED's.
Everything is running fine but I think I may have messed up the wiring connecting the raspberry pi.

For reference in the photos.

- 5V 10A power supply into the breadboard
- A low level logic converter with 5v connection and two grnd connections
- Power connection from led to + and - of breadboard
- Data connection from GPIO 18 to breadboard and data connection of LED on same row
- Grnd and 5v connection from raspberry pi

![IMG_9065](https://user-images.githubusercontent.com/42615862/62319531-2dd65680-b46c-11e9-8bc4-b93ab72a873d.JPG)
![IMG_9066](https://user-images.githubusercontent.com/42615862/62319532-2dd65680-b46c-11e9-85be-31c8e12dcce7.JPG)
![IMG_9067](https://user-images.githubusercontent.com/42615862/62319533-2e6eed00-b46c-11e9-8e34-a727a90b1a06.JPG)

**Comment by gaijinsr** [comment]
Looks to me like you are shorting out the two power supplies...
Either remove the connection between 5V on the RPi and the breadboard or remove one of
the two power supplies, preferably the smaller one on the RPi.

**Comment by joeybab3** [comment]
@schrotbe2021 Has @gaijinsr's fixes helped at all?

**Comment by schrotbe2021** [comment]
> @schrotbe2021 Has @gaijinsr's fixes helped at all?

Yes! Sorry for the delay. I removed the 5V on the RPi and started up fine.
