### ISSUE TITLE
Buster + IQaudIO card

### ISSUE THREAD

**Issue by NickSutton** [scottlawsonbc/audio-reactive-led-strip#226]
Hey,
Firstly great job! I decided to see what I could get working before ordering a new set of parts for this. I’m currently building an AirPlay speaker solution using Shairport-Sync and have that working well. I’d like to add your awesome visualisation setup to my project, but have a couple of questions:

1) I’m running raspbian buster and some of the files to do with audio config you describe no longer exist :-(

2) To get decent audio quality I’m using an iQaudioIO Pi-DAC board, I plugged in a USB mic/speaker dongle I had laying around and added a splitter to the IQaudIO output and surprising the USB mic (wired to the output of the iQaudioIO splitter) did record, so that’s promising that the pi can get the output back as the input for the visualisation.... However, when I ran some of the test .py files, my audio output stopped completely and had to be rebooted before it was happy.... Is there a way to get the two to play nicely together?

3) I’d like to see this setup working before I buy the LEDs, how do i run the GUI on the pi?

Great work on your project!
Cheers,
Nick

**Comment by NickSutton** [comment]
Just by way of an update, question 1 was resolved by actually downloading the repo, so that helped!

Question three I guess I’m asking can I run the GUI without the LEDs installed? St the minute it craps out with pages of errors related to the IQAudio device (will copy when I’m back on the machine).

I feel optimistic!

**Comment by joeybab3** [comment]
You are able to run the GUI and it will display even if there is no Arduino connected, it basically just sends the UDP packets to a nonexistent device and so they get discarded but sometimes I just like to run the GUI because it looks cool even without the lights.

**Comment by NickSutton** [comment]
Thanks, should have mentioned, am looking at using pi in standalone mode!

**Comment by NickSutton** [comment]
Hey, so here’s what happens when I run `sudo python visualisation.py`

As stated I’m using Shairport-sync to receive the audio from iPhone to Raspberry Pi (working well)
And I’m physically feeding the audio output from the IQaudio pi-DAC+ to a USB mic in.

Any ideas?

`ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.front.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.IQaudIODAC.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
`

**Comment by NickSutton** [comment]
Here is my `aplay -l` output showing both of the cards (IQaudIO for output, and USB audio for the mic) correctly loaded, so I’m not sure why I’m seeing so many errors?:

`**** List of PLAYBACK Hardware Devices ****
card 0: IQaudIODAC [IQaudIODAC], device 0: IQaudIO DAC HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

**Comment by joeybab3** [comment]
What did you end up doing to solve it?

**Comment by NickSutton** [comment]
Followed the instructions properly! I had been avoiding setting the USB audio device as the default because I’d like to use my IQAudio card as the output, but that’s for another day.

Glad to see it working, now just need to tweak it to my own set up

On 13 Aug 2019, at 20:52, Joey Babcock <notifications@github.com<mailto:notifications@github.com>> wrote:


What did you end up doing to solve it?

**Comment by NickSutton** [comment]
IF anyone comes here in the future wanting to use RPi with an external (HAT) sound card such as the IQaudIO DAC+ and are streaming music to your device with shairport-sync, then, to get this running follow the install instructions. Buy a USB mic (not a sound card). 

Then set Shairport-sync to pipe it’s audio to the non-default device (in my case the IQaudIO board).  There is a specific setting for this in the alsa options.

So now, I have a USB mic listening to my music and generating the visual actions. I’m sure there’s a ‘virtual’ way of doing all this but would probably require some significant work.

Cheers
