### ISSUE TITLE
New to Arduino, not sure where to go from here

### ISSUE THREAD

**Issue by MackRhine** [scottlawsonbc/audio-reactive-led-strip#227]
Error Message:

Arduino: 1.8.9 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 160 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\Mack\Desktop\music_visualizer\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266 - Copy.ino:15:15: error: redefinition of 'const uint8_t PixelPin'

 const uint8_t PixelPin = 3;  // make sure to set this to the correct pin, ignored for Esp8266(set to 3 by default for DMA)

               ^

ws2812_controller_esp8266:15:15: error: 'const uint8_t PixelPin' previously defined here

 const uint8_t PixelPin = 3;  // make sure to set this to the correct pin, ignored for Esp8266(set to 3 by default for DMA)

               ^

C:\Users\Mack\Desktop\music_visualizer\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266 - Copy.ino:18:13: error: redefinition of 'const char* ssid'

 const char* ssid     = "YOUR_WIFI_SSID";

             ^

ws2812_controller_esp8266:18:13: error: 'const char* ssid' previously defined here

 const char* ssid     = "[MY WIFI SSID";

             ^

C:\Users\Mack\Desktop\music_visualizer\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266 - Copy.ino:19:13: error: redefinition of 'const char* password'

 const char* password = "YOUR_WIFI_PASSWORD";

             ^

ws2812_controller_esp8266:19:13: error: 'const char* password' previously defined here

 const char* password = "[MY PASSWORD]";

             ^C:\Users\Mack\Desktop\music_visualizer\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266 - Copy.ino:20:14: error: redefinition of 'unsigned int localPort'

 unsigned int localPort = 7777;

              ^

ws2812_controller_esp8266:20:14: error: 'unsigned int localPort' previously defined here

 unsigned int localPort = 7777;

              ^

C:\Users\Mack\Desktop\music_visualizer\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266 - Copy.ino:21:29: error: redefinition of 'char packetBuffer [1024]'

 char packetBuffer[BUFFER_LEN];

I'm using this board: https://www.amazon.com/gp/product/B071YPS666/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1

I'm very new to arduino and am not sure where to go from here. Does anyone know what's wrong?

**Comment by joeybab3** [comment]
Can you post ws2812_controller_esp8266 - Copy.ino for us?
