### ISSUE TITLE
Is that possible use ethernet and not wifi?

### ISSUE THREAD

**Issue by andreseichi** [scottlawsonbc/audio-reactive-led-strip#228]
Sometimes my wifi get really bad and then the leds lights get really laggy. Have wifi problem here, but with ethernet won't be a problem.

**Comment by richyxi** [comment]
Are u using an esp?

**Comment by andreseichi** [comment]
yeah, exactly the same of the photo, esp8266.

But what if I use the ethernet module with the esp or an arduino? i don't know...

**Comment by richyxi** [comment]
Are u going to try it?

**Comment by richyxi** [comment]
Let me know if that works, btw which ethernet module are refering to

**Comment by andreseichi** [comment]
Want to. But wanna know first if that's possible

**Comment by andreseichi** [comment]
Rj-45

**Comment by joeybab3** [comment]
If you rewrite the Arduino sketch it would be possible but for right now we are not looking to add that functionality into the main project.
