### ISSUE TITLE
Visualization.py graphs when no audio?

### ISSUE THREAD

**Issue by NickSutton** [scottlawsonbc/audio-reactive-led-strip#232]
Hi, so i got the RPi to show the visualizations on screen. Pretty cool!!

One thing though, they seem to be dancing away by themselves... Even with no audio playing the lines are all the place!

To get it all working I just had to set the USB audio as the default device but I really need my IQAudio card as the default output and the USB as the default input - Is this achieveable? Or, is it going to be easier just to mount a USB mic in the speaker box rather than hardwiring the audio from a spare output to the mic in port?

Can’t wait to get this fully up and running! 

Cheers,
Nick

**Comment by joeybab3** [comment]
The visualization tries to add a sort of gain to the audio when it's quiet to deal with microphones that don't pick up audio well, and in doing so it will continue to add gain until it either starts detecting something or hits the threshold. 

What you are seeing is basically the background noise or interference that is being amped up until it reaches the threshold or shuts off.

**Comment by joeybab3** [comment]
As far as your other questions, I do not own a rpi so I can't assist but its possible someone may have figured that out in another issue?

**Comment by NickSutton** [comment]
Thanks man, I have looked and the question has been posed on the RPi forums but no one answered. I need to dig in to the asound file and see what’s what. Thanks for the quick reply

**Comment by NickSutton** [comment]
Hi, I currently have `MIN_VOLUME_THRESHOLD = 1e-7 ` For the threshold value, can you offer any advice on how I stop the LEDs triggering on ‘background noise’?

I’m driving the LED’s directly from the speakers (cabled in to the mic-in port on a USB sound card) so technically there shouldn’t be any background noise... Any advice appreciated!

**Comment by tungheo** [comment]
MIN_VOLUME_THRESHOLD = 1e-2 work for me
