### ISSUE TITLE
[SOLVED] Wiring Help

### ISSUE THREAD

**Issue by dbourdeveloper** [scottlawsonbc/audio-reactive-led-strip#238]
__Description__
I'll admit that I'm a bit of a beginner when it comes to circuits. Here's my setup below. I had a 150 LED W2812 to which I cut 113 out , leaving me with 37 LEDS. I had a level converter there just in case I needed it, but didn't use it. The application and LEDs are *working* but it seems to mostly "react" on the first 10 or so LEDs while everything on gets modified once in awhile.
![ESp8266](https://user-images.githubusercontent.com/10367546/65748914-d6461700-e0b9-11e9-9032-8341cc1157a2.jpeg)

In case the image isn't clear, the ESP8266 is powered through a USB from my computer and the LEDs from a variable power supply set to 5V.

I can't help but wonder if my circuits are incorrect since I'm getting erratic behaviors with the LED instead of the smooth animations I see in the demo videos.

**Comment by SealedJoy** [comment]
Likely a grounding issue, try connecting the wemos gnd to powersupply gnd

**Comment by dbourdeveloper** [comment]
> Likely a grounding issue, try connecting the wemos gnd to powersupply gnd

It was definitely a grounding issue. Thanks @SealedJoy
