### ISSUE TITLE
Can't compile hardware to ESP8266

### ISSUE THREAD

**Issue by PelegPLT** [scottlawsonbc/audio-reactive-led-strip#240]
Arduino: 1.8.10 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 160 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 9600"

ws2812_controller_esp8266:23:8: error: 'WS2812' does not name a type

 static WS2812 ledstrip;

        ^

ws2812_controller_esp8266:24:8: error: 'Pixel_t' does not name a type

 static Pixel_t pixels[NUM_LEDS];

        ^

C:\Users\HHHH\Desktop\dancyPi-audio-reactive-led-master\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266.ino: In function 'void setup()':

ws2812_controller_esp8266:49:5: error: 'ledstrip' was not declared in this scope

     ledstrip.Begin();//Begin output

     ^

C:\Users\HHHH\Desktop\dancyPi-audio-reactive-led-master\audio-reactive-led-strip-master\arduino\ws2812_controller_esp8266\ws2812_controller_esp8266.ino: In function 'void loop()':

ws2812_controller_esp8266:69:13: error: 'ledstrip' was not declared in this scope

             ledstrip.SetPixelColor(N, pixel);

             ^

ws2812_controller_esp8266:71:9: error: 'ledstrip' was not declared in this scope

         ledstrip.Show();

         ^

Multiple libraries were found for "ESP8266WiFi.h"
 Used: C:\Users\HHHH\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.1\libraries\ESP8266WiFi
Multiple libraries were found for "NeoPixelBus.h"
 Used: C:\Users\HHHH\Documents\Arduino\libraries\NeoPixelBus_by_Makuna
Multiple libraries were found for "SPI.h"
 Used: C:\Users\HHHH\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.1\libraries\SPI
exit status 1
'WS2812' does not name a type

**Comment by joeybab3** [comment]
I'm not super sure where you're getting the code you're compiling from here as there is no longer a line that looks like 
`static WS2812 ledstrip;`

That is because we've moved to a new ws2812 library. 

Please update the code to the latest from this repo and try running it again.

**Comment by joeybab3** [comment]
Let me know if you're still having problems otherwise I'll assume it's solved and close this issue.

**Comment by joeybab3** [comment]
Closing since there hasn't been a response from OP in a year or so.
