### ISSUE TITLE
NodeMCU isn't receiving any data 

### ISSUE THREAD

**Issue by inange** [scottlawsonbc/audio-reactive-led-strip#244]
Esp8266 ip,port etc. is configured right
visualizer on pc works no problem.

But Esp8266 decided not to work ¯\_(ツ)_/¯ 
any help will be appreciated

**Comment by Ryuiku** [comment]
Assuming the visualizer part on the pc is configured right (it needs to know where to send the data), you could try using WireShark to see what data is going to and from the esp8266’s ip and or your pc’s ip. I’d do that to confirm if the esp is responsive, and to make sure the pc is sending data.

**Comment by biejay** [comment]
Did you already do a Strandtest to check if the wiring for the LEDs is correct?
And then i would try to adjust the arduino code and then check the serial output if the connection is working fine.
Would check those 2 things first.

**Comment by joeybab3** [comment]
As @biejay has requested, please run strandtest and let us know how it goes.

Can you give me some more info like what you mena by not receving any data?

Is it displaying fps in the serial monitor or does it stay at FPS: 0?

**Comment by inange** [comment]
sorry for not posting back but problem solved itself but thanks everyone for helping anyways
