### ISSUE TITLE
Changing colors?

### ISSUE THREAD

**Issue by BButner** [scottlawsonbc/audio-reactive-led-strip#250]
So this isn't an issue, however I didn't really know how else to actually ask this so here we are.

I've got a Rapsberry Pi 4 4GB and got this up and running on it and its working *very* smoothly, however my main question, is there any way to change which exact colors the LED's actually display? The project that I'm working on for this, I want to have it really use green, white, and red. Any ideas on how that could be accomplished?

**Comment by denisTenis1** [comment]
Mess around with led.py, I think thats where the colors are selected

**Comment by boland25** [comment]
so the LED colors are values that are written to a numpy array called pixels in the led.py file.  you could intercept the place where those values are written and put in your own.  Or you could always skew them to be of green, white red values by scaling the r g b respectively in the led.py file
