### ISSUE TITLE
What michrophone/speakers are best for  leds best performance?

### ISSUE THREAD

**Issue by denisTenis1** [scottlawsonbc/audio-reactive-led-strip#253]
I noticed while testing my LEDs to the demo video Scott made that it doesn't match up, what would me the best michrophone/speakers for this?

**Comment by d00mfish** [comment]
So you use a microphone? I'd recommend using a usb soundcard and feeding the signal directly per 3,5mm Jack into your computer/rpi. Since the program sets the gain automtatically I would assume that every soundcard goes well with it.

**Comment by denisTenis1** [comment]
> So you use a microphone? I'd recommend using a usb soundcard and feeding the signal directly per 3,5mm Jack into your computer/rpi. Since the program sets the gain automatically I would assume that every soundcard goes well with it.

Will I get better results with a soundcard? Do you use a soundcard? I thought everyone was using microphones

**Comment by d00mfish** [comment]
I tried both and for what I can say is the result with a soundcard is way better than with a microphone. Makes sense because the pc/pi gets the signal without interference and in full dynamic range (20-22kHz).
Also you have to play a little with your frequency range. I use it for bass visualization and therefore set it to 50-400Hz. Looks great!

**Comment by denisTenis1** [comment]
What soundcard do you recommend? And also, I don't understand how can a
soundcard power the code, isn't a soundcard something you plug your mic or
speakers into?

2019-12-13, pn, 12:06 Leo <notifications@github.com> rašė:

**Comment by denisTenis1** [comment]
> I tried both and for what I can say is the result with a soundcard is way better than with a microphone. Makes sense because the pc/pi gets the signal without interference and in full dynamic range (20-22kHz).
> Also you have to play a little with your frequency range. I use it for bass visualization and therefore set it to 50-400Hz. Looks great!

Still waiting for your reply :D

**Comment by d00mfish** [comment]
Oh sorry I didn't see your message. Most soundcards will funktion if you configure teh Raspi like mentioned in the readme. Though there are some cards that don't work, buying a 3$ card from ebay should do the trick. Mine is about 9 Years old but works like a charm. The soundcard does the same like any usb microphone. The advantage is that the Sound does not need to travel through the air so the signal is much cleaner and better. I hope that helped you and sorry for the late reply :)

**Comment by denisTenis1** [comment]
Thanks for replying,
Will the soundcard work with the pc version, I have a Raspberry Pi 3 laying
around if it doesn't though.

**Comment by d00mfish** [comment]
Yes it will. Just stick to the Readme and you should do nothing wrong.

**Comment by joeybab3** [comment]
Seems like this was solved, closing.
