### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by billz-net** [scottlawsonbc/audio-reactive-led-strip#263]
In the article, you say to edit config.py but don't indicate where it is.  Doesn't seem to be in any of the new directories created by the install.

**Comment by andres91-gif** [comment]
it is if you go to directory: cd audio-reactive-led-strip/python/config.py

**Comment by andres91-gif** [comment]
sorry, my mistake
cd audio-reactive-led-strip/python
sudo nano config.py

**Comment by joeybab3** [comment]
As mentioned above it is in the python directory of the repository, so enter it wherever you cloned or downloaded it.
