### ISSUE TITLE
Immediate switch off and strobe

### ISSUE THREAD

**Issue by knichol** [scottlawsonbc/audio-reactive-led-strip#267]
Hey!
I'm currently tweaking the code a bit to add more functionality to the GUI.
I wanted to add an Off and a Strobe function. I have the buttons etc all hooked up and displaying correctly on the GUI.
For the Off function I copied the scroll functions but just set the array values to 0 which gradually turns off the LEDs. Does anyone know how I might be able to completely switch off all the LEDs from the context of the GUI?
Also I want to try build a strobe type function into the visualization.py code. I tried reworking the spectrum function to output an array of 255, 255, 255 but it didn't really work. Has anyone any ideas how I might accomplish that kind of functionality?
Thanks!

**Comment by not-matt** [comment]
Hi, this numpy function is probably what you're looking for

https://stackoverflow.com/a/20606278

**Comment by knichol** [comment]
nailed it. got both functions working, thanks!
