### ISSUE TITLE
APA102

### ISSUE THREAD

**Issue by Suspect-byte** [scottlawsonbc/audio-reactive-led-strip#271]
Hi guys, 
I am new to this and I found a few things first of all I have a 4 wire cable called Dotstar. I got the APA102. Now I want to use this script with Hypercon to make a bias and audio led strip. I installed the Adafruit dotstar and Adafruit Blinka (because apparently you need those). But I have no clue on how to get these things working. I know which GPIO pins I need but don't know how to get the software working. I got a RPI4 and RPI3b. So I can chose 1 of those. Can somebody help me out a step by step guide. Because the WS281x software (obviously doesn't work for the apa102).

**Comment by joeybab3** [comment]
If you have an apa102 library that supports setting pixel colors via r,g,b then you can import the library and replace the line at 

`RgbColor pixel((uint8_t)packetBuffer[i+1], (uint8_t)packetBuffer[i+2], (uint8_t)packetBuffer[i+3]);//color`

With your function.

**Comment by Suspect-byte** [comment]
@joeybab3 Thanks for you response! As is said I am kinda nooby with this so would you mind explaining. I have successfully installed the apa102-pi library "https://github.com/tinue/apa102-pi".
In the link, they say I need to install Adafruit_Python_GPIO, but when I go to the site they say that is has been deprecated for Adafruit-Blinka. So my first question do I need to install the Adafruit_Python_GPIO or not? Secondly, how do I change it with my function and where can I find the file to change it? So my APA102 would work with a CLK and DATA wire. 

Thanks in advance!

**Comment by joeybab3** [comment]
@Suspect-byte I do not own an APA102 strip so I can't really test for it. Check #162 it seems they discussed it a bit there as well.

**Comment by joeybab3** [comment]
Closing this as it's already addressed in #162, if you have more questions please ask them there.
