### ISSUE TITLE
Multiple strips with different lengths

### ISSUE THREAD

**Issue by martenumberto** [scottlawsonbc/audio-reactive-led-strip#275]
Hello.

I want to run more than one stripe. I want to connect them in series so that there is no address issue.
Can I tell the software that Led 1-35 is Stripe 1, LED 36-100 Stripe 2 and LED 100-180 Stripe 3?
The issue is that the scaling is different when i connect them in parallel due to dubble addresses. 

Thx :)

**Comment by joeybab3** [comment]
I'm not sure what you're asking here. Do you want to run multiple strips that are showing the same data?

**Comment by jbonnett92** [comment]
@joeybab3 I would like the ability to add more than one strip too, so assign more than one GPIO. Also split the LED pixels into groups, say strip 1 (300 pixels) only selecting the last 50 and selecting 50 from strip 2 adding an effect based on a different frequency.

**Comment by joeybab3** [comment]
> @joeybab3 I would like the ability to add more than one strip too, so assign more than one GPIO. Also split the LED pixels into groups, say strip 1 (300 pixels) only selecting the last 50 and selecting 50 from strip 2 adding an effect based on a different frequency.

You can do that relatively easily in the arduino sketch by adding a check for the index of the pixel in the main loop

**Comment by jbonnett92** [comment]
@joeybab3 Arduino sketch? I'm not using the ESP8266.

**Comment by joeybab3** [comment]
@jbonnett92 Then change it in the python script, I do not have a pi so I am unable to help with that part
