### ISSUE TITLE
"ImportError: No module named neopixel" EDIT: Two Fixes for the ReadMe

### ISSUE THREAD

**Issue by d00mfish** [scottlawsonbc/audio-reactive-led-strip#277]
I tried to follow the ReadMe and I made countless setups with RPi3B, RPi3A, RPi4 and even Zero. But for some reason it doesnt work anymore.
The Library in the readme is for Arduino as far as I can seeso I don't know how to install it.
The rpi_ws281x library removed the error but the led output is random blinking like using no logic level shifter (i use one). I checked every wire at least 5 times and with my Pi3A it works like a charm.
I know how hard it is to make a diagnosis with this little of information but I really have no Idea what it may be.
If you have questions just ask and thanks a ton for all your work to keep this awesome project alive! <3

**Comment by d00mfish** [comment]
Ok I looked at earlier versions of the readme and there was a more detailed description of how to install the rpi_ws281x library

`Install ws281x library

To install the ws281x library I recommend following this Adafruit tutorial.

sudo apt-get install build-essential python-dev git scons swig
git clone https://github.com/jgarff/rpi_ws281x.git
cd rpi_ws281x
scons
cd python
sudo python setup.py install
`
that was the information I needed.
Maybe you could look into the current ReadMe file and fix this, or I am just very confused and my issue is void.
Anyway have a good day :)

**Comment by d00mfish** [comment]
Oh and the command for the default usb device has a ":" at the end that shouldn't be there.

> sudo nano /usr/share/alsa/alsa.conf:

to 

> sudo nano /usr/share/alsa/alsa.conf

**Comment by joeybab3** [comment]
@d00mfish I'll look into improving the readme, thanks for the input.

**Comment by joeybab3** [comment]
I believe I've since fixed these and just forgot to update this issue, closing now.
