### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by karthushuang** [scottlawsonbc/audio-reactive-led-strip#280]
when i run the visualization.py in the program, it shows me cannot connect to X server. if i disable GUI, program tells me there is a invad sample rate

**Comment by joeybab3** [comment]
Can you explain your issue in a little more detail? A screenshot would also help.

What's your setup looking like and what platform are you using?

**Comment by zilahir** [comment]
most likely this means you have the `GUI` set to to `true`, and don't have `xhost`, so just disable the `gui` in the `config.py`

**Comment by joeybab3** [comment]
@karthushuang Let me know if there's anything more you need help with, for now, I'm closing this.
