### ISSUE TITLE
GUI Could not connect to any X display 

### ISSUE THREAD

**Issue by LuiCheese** [scottlawsonbc/audio-reactive-led-strip#287]
When using the GUI set to true I get an error that says:

PuTTY X11 proxy: Unsupported authorisation protocol
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:10.0
Could not connect to any X display.

I am using Xming server with putty x11 forwarding turned on and all the other ssh_config uncommented, not really sure what is wrong,

**Comment by joeybab3** [comment]
It's trying to display the visualization which it can't do if you're on a tty. 
Disable the visualization and it should work.
