### ISSUE TITLE
Use GPU FFT on Raspberry Pi

### ISSUE THREAD

**Issue by steveway** [scottlawsonbc/audio-reactive-led-strip#29]
The Raspberry Pi has a hardware accelerated way to do FFT:
http://www.aholme.co.uk/GPU_FFT/Main.htm
And there are a few different ways to do this from Python:
https://github.com/colin-guyon/rpi-audio-levels
For example lightshowpi uses this for its FFT calculations:
https://bitbucket.org/togiles/lightshowpi/src/94e76f67cb9df59990acfe9a4e7eb4a443d1668c/py/fft.py?at=master&fileviewer=file-view-default
Using that would certainly would be helpful for this too.

**Comment by scottlawsonbc** [comment]
Thanks! I was aware of GPU_FFT but I did not know about those implementations. I appreciate you finding those links as they will be a helpful reference.

I'll do some testing and consider using GPU_FFT if the performance is noticeably better. Right now the two main performance bottlenecks are FFT and an expensive [numpy.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) function call.
