### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Ratbagdoo** [scottlawsonbc/audio-reactive-led-strip#297]
I've installed NumPy through conda (as well as everything else) and yet this issue still stands.

where can I find this module?

**Comment by joeybab3** [comment]
pip install numpy or pip3 install numpy depending on version, you may also need to do conda install numpy

**Comment by Kdcius** [comment]
Hello !
I have the same issue and can't get rid of it.
Do you find any way to get trough it ?

**Comment by Ratbagdoo** [comment]
Ye I uninstall it from both python & anaconda then installed the latest version available with anaconda.
