### ISSUE TITLE
Chinese ESP8266 clone works as a unsecured hotspot unless you add a line of code into ws2812_controller_esp8266.ino

### ISSUE THREAD

**Issue by NotUnderi** [scottlawsonbc/audio-reactive-led-strip#298]
I tried the provided arduino code with a "Makershop NodeMCU V3.4" that I received in the mail a few days ago and it seems that at least these chinese clones work as a hotspot unless you add a line of code in setup function. Fixed it by adding`WiFi.mode(WIFI_STA);`in setup function. Seems to be working fine like this.
https://github.com/scottlawsonbc/audio-reactive-led-strip/blob/38502b47b482e66fc27981398a538ecefee85ee3/arduino/ws2812_controller_esp8266/ws2812_controller_esp8266.ino#L34-L52

**Comment by joeybab3** [comment]
Yeah, this will happen any time the previous sketch was running in AP or STA_AP mode, most sketches I've seen leave it up to the user to have the correct mode but adding that line doesn't add any complexity to the sketch so I will get to that rn.
