### ISSUE TITLE
2x LED Strips with same amount LEDs - Color Problem

### ISSUE THREAD

**Issue by SergeantOG** [scottlawsonbc/audio-reactive-led-strip#299]
Hi, 

i got two LED stripes paralell with the **same amount** of LEDs. One is working fine, the spectrum effect is purple but on the other LED stripe it uses all colors... The spectrum effect is working 

What can cause the problem?

**Comment by gaijinsr** [comment]
My guess is that one of the strips is RGB (or BGR or whatever) and the other one is RGBW, i.e. it expects four values per pixel. Sending RGB data to such a strip means that it takes the R value of the second pixel as the white value of the first, the GB of the second and the RG of the third for its second pixel... Those two strips cannot be used in parallel.

**Comment by SergeantOG** [comment]
Sorry to mention but the second strip is just the left over from the first one. 

But somehow it fixed itself after executing  the led.py
