### ISSUE TITLE
Purple spectrum

### ISSUE THREAD

**Issue by rbirkby** [scottlawsonbc/audio-reactive-led-strip#30]
When using spectrum mode I notice the green LEDs don't turn on very often - consequently, the colors are mostly purple. If I check the GUI visualization, it shows the same:

![image](https://cloud.githubusercontent.com/assets/203034/22644629/37c447aa-ec5b-11e6-9a21-723cbffc9011.png)

However, this is not the output shown in the GIF embedded in the README - in that case, the green channel lights regularly.

RPi3, 300 LED 5m ws2812, 5V level shifted. CPU has 1 core at 90% most of the time. FPS reduced to 28.

**Comment by scottlawsonbc** [comment]
Thanks for the report, a few other people have mentioned this as well.

> However, this is not the output shown in the GIF embedded in the README - in that case, the green channel lights regularly.

The GIF in the README was recorded using an earlier version of the visualization software so you should not expect to see the exact same output.

I'm not very happy with the purplish spectrum effect either. I'm working on an improved version with a much better color assignment algorithm.

I recently [recorded a demo video of the new spectrum effect](https://www.youtube.com/watch?v=WJRzbbOui0c). I'm in the final stages of testing and this version should be released in the next week or two. Do you like this version more than the current version?

**Comment by rbirkby** [comment]
That visualization looks great. My current setup looks like:

https://www.youtube.com/watch?v=lj1yhpyGnT4

**Comment by scottlawsonbc** [comment]
Wow! I love the Alexa integration, that is such a convenient way to control the visualization. How did you do it?

**Comment by rbirkby** [comment]
There are links to the server-code + DevOps templates in the description of the video.
As for the changes to your visualization code, they are minor and simply set up an IoT subscription using the AWS IoT Python SDK then update the visualization in the same way as the GUI:

```python
    def callback(client, userdata, message):
        global visualization_effect

        payloadDict = json.loads(message.payload)
        if payloadDict["message"] == "scroll":
            visualization_effect = visualize_scroll
        if payloadDict["message"] == "spectrum":
            visualization_effect = visualize_spectrum
        if payloadDict["message"] == "energy":
            visualization_effect = visualize_energy


    myMQTTClient = AWSIoTMQTTClient("ReactiveLeds")
    myMQTTClient.configureEndpoint("a2wkex2gd7mljx.iot.eu-west-1.amazonaws.com", 8883)
    myMQTTClient.configureCredentials("root-CA.crt", "ReactiveLeds.private.key", "ReactiveLeds.cert.pem")
    myMQTTClient.connect()
    myMQTTClient.subscribe("commands", 1, callback)
```

**Comment by scottlawsonbc** [comment]
Thanks for the information. I'll be updating the documentation when I release the next version. I should add a note about this in the README.

Let me know if you have suggestions or feedback about the visualization software in general. In your video, the scroll effect doesn't seem to scroll very quickly when using 300 LED. I should make the scroll speed a percentage of the total strip length instead of a fixed number of pixels per second.

**Comment by rbirkby** [comment]
Yes, the led strand test is also very very slow!!! I reduced the delay when I tested my strip. 

As long as the GUI is decoupled from the visualisation, it should be easy to add other control mechanisms.
