### ISSUE TITLE
Spectrum Visualization Purple/White 

### ISSUE THREAD

**Issue by ColeSlawCole** [scottlawsonbc/audio-reactive-led-strip#308]
Hey everyone really loving this project! I noticed that there doesn't seem to be a lot of green that occurs in the spectrum visualization and that it looks mostly white or purple. I looked for other posts about it and found #54 and #30. There was mention of a fix and I'm not sure if that every got uploaded or if I someone have an older revision that the current. Any help would be appreciated! Thanks!

**Comment by joeybab3** [comment]
I think that the code was updated since then but may still show inadequate color diversity.
You could attempt to bump the green up a bit in the code with a fixed scalar but I'm not sure of any solutions to get the algorithm to do it on its own.
