### ISSUE TITLE
Can't start visualization on MacOS with Loopback 

### ISSUE THREAD

**Issue by aluchianic** [scottlawsonbc/audio-reactive-led-strip#311]
System:
MacOs Big Sur
NodeMCU v3 
Led-strip WS2812
Loopback 

Hey there, trying to use your library but when i trying to start `python3 python/visualization.py` i get following error and GUI doesn't starts:

<img width="1680" alt="Screenshot 2020-12-19 at 18 33 40" src="https://user-images.githubusercontent.com/36815189/102694406-8527c300-4229-11eb-8eb9-bf7e4bb203bb.png">

on screenshot command is `python3 python/visualization.py` but i getting same error with `python3 python/visualization.py /tmp` 

 seems that your lib can't find Virtual Audio Input of Loopback (i were getting same error when just installed all python dependencies and tried to run `python3 python/visualization.py` without Loopback setup). Didn't found any issues like mine, any advice please. 
 
 <img width="834" alt="Screenshot 2020-12-19 at 18 40 06" src="https://user-images.githubusercontent.com/36815189/102694446-bd2f0600-4229-11eb-8097-6e72b02ea5a5.png">
<img width="1207" alt="Screenshot 2020-12-19 at 18 34 56" src="https://user-images.githubusercontent.com/36815189/102694443-ba341580-4229-11eb-874f-752ed8f5f284.png">
<img width="673" alt="Screenshot 2020-12-19 at 18 35 04" src="https://user-images.githubusercontent.com/36815189/102694445-bc966f80-4229-11eb-92c7-c9d214609093.png">

**Comment by osbash** [comment]
I had a similar issue, something to do with Big Sur.

Run these:
brew uninstall portaudio
brew install portaudio --HEAD

Should fix it

**Comment by aluchianic** [comment]
@osbash yeah, reinstalling `portaudio` helped
