### ISSUE TITLE
Unsecured wifi mode fix not included in code for some reason.

### ISSUE THREAD

**Issue by TheUNkilled123** [scottlawsonbc/audio-reactive-led-strip#315]
So the WiFi.mode(WIFI_STA); line seems to be removed from the setup function in the esp8266 code even though the latest commit is the one adding it. Not sure if it's intentional or if it's been removed by a mistake. The issue I'm referencing is #298 .

**Comment by joeybab3** [comment]
Alright should be good, not sure how I missed that but thanks for pointing it out.
