### ISSUE TITLE
Link to Dancy Pi in readme?

### ISSUE THREAD

**Issue by VonHirsch** [scottlawsonbc/audio-reactive-led-strip#323]
Hello, could you put a link to Dancy Pi in your readme?  He's giving you full credit, and has a Python 3 port working.  Thanks for this!

https://github.com/naztronaut/dancyPi-audio-reactive-led

**Comment by joeybab3** [comment]
I need to email Scott and figure out what the status of this project is. At the current moment I don't have the knowledge or ability to bring this project where it should be so I'm just trying to help with issues and whatnot.

If we decide to put this project into a not maintained status I'll probably add a section near the top with links to forks or alternative projects that fulfill a similar role.

**Comment by VonHirsch** [comment]
any updates on this?

**Comment by joeybab3** [comment]
No, at the moment I don't see a real reason to add a single alternative project to the readme.

**Comment by VonHirsch** [comment]
ok no worries.

about no reason... have you actually looked at the [other repo](https://github.com/naztronaut/dancyPi-audio-reactive-led)?  and [website](https://www.easyprogramming.net/raspberrypi/audio_reactive_led.php)?

**Comment by joeybab3** [comment]
Yes, other repos have more features or are better maintained., I understand that.

My point earlier is that as of right now I am the sole maintainer as Scott hasn't been able to get around to it. I fix the readme and answer questions as best I can about this repo but until I know for sure that this repo is going to be unmaintained, I don't want to declare it dead.

**Comment by VonHirsch** [comment]
ok sure, totally understand.  No pressure.
