### ISSUE TITLE
random colors and number of pixels fails

### ISSUE THREAD

**Issue by exiction** [scottlawsonbc/audio-reactive-led-strip#325]
Hey,
NOTE: my script ist completely okay.

When I start the visualization.py it will light up random leds and the number of pixels is also wrong:
I changed *num_pixels* to 100, but all my 300 LEDS will light up randomly.
My GUI is okay, but it's not transferred to the LEDS correctly..
The color and position of LEDs also update after ~1 second.

I dont know whats going on can someone help me?

**Comment by acopeland** [comment]
Make sure your led strip and microcontroller share a common ground. You are describing behavior that typically occurs when there is no common ground. Post back here if it's already sharing a common ground, then we can go from there.

**Comment by callmefxur** [comment]
Sure, but I have a new problem.. I got "No audio input. Volume below threshold: Volume 0.0" and I changed the threshold in config.py and changed my headset. Also activated my microphone (I use "C-Media USB Headphone Set")

**Comment by joeybab3** [comment]
What is your default input device?

**Comment by callmefxur** [comment]
Im using a Headset ("C-Media USB Headphone set" and this is default)

In my config.py:

`MIC_RATE = 44100
MIN_VOLUME_TRESHOLD = 1e-`
