### ISSUE TITLE
Nothing happen in led strip

### ISSUE THREAD

**Issue by ashii25** [scottlawsonbc/audio-reactive-led-strip#329]
Its day 10 and my 2nd node mcu device.....all process done well ...but when uploading the code the led glows in white not full but first the front one and then increase as uploading percentage goes up...the light strip glows around 50 sometime 40 led out if 60 un white and stays... visualization also racting on music but nothing happens in led strip... I use voice meter i dint use any mic but when i its still cant work.. basically led is not reacting to visualization...also esp8266 and pc connected to sane network..config.py ip also same but still nothing happening in led...wled webserver works fine... connection are also good and used all recommend parts...also strand test working fine...wled web server effect working fine also Ambilight ,music vu meter like projects also not working it is the new node mcu i returned the previous one coz of this issue

**Comment by fildaw** [comment]
Do you see information about successful connection to wifi network ('Connected to...') in the serial monitor of your nodemcu on your computer or only dots?

**Comment by ashii25** [comment]
> Do you see information about successful connection to wifi network ('Connected to...') in the serial monitor of your nodemcu on your computer or only dots?

It was only dots but i find a post in closed issue cases the fix is you have to change your ip to node mcu ip in config.py and in sketch the default config.py ip is different if visualization is working but led strip not working then you have to change ip in config.py and in sketch to esp8266 ip then it will connect to same network as pc

**Comment by ashii25** [comment]
Fixed
