### ISSUE TITLE
How to react only to the beat of the music w/o changing colors

### ISSUE THREAD

**Issue by KaitoKid** [scottlawsonbc/audio-reactive-led-strip#33]
Absolutely love this project so far, and I've been trying to add a different configuration to look something along the lines of this: https://www.youtube.com/watch?v=IXrsiUs37Jg&feature=youtu.be

Can you give me some pointers on how to navigate your code (which is already extremely well documented) to maybe figure something like this out?

Thanks!

**Comment by scottlawsonbc** [comment]
I don't quite understand, could you tell me more about what you are wanting to do?

You might be interested in the new version that I've been developing in the develop branch. The code is working but has limited features and documentation (no GUI, one effect) at this point. I've significantly improved the spectrum effect in the new version, and [you can see a demo video here](https://www.youtube.com/watch?v=WJRzbbOui0c&).

Unfortunately, I won't have time to finish the release for another month or two.

**Comment by KaitoKid** [comment]
Sorry, should've clarified a bit more. I'm wondering if it's possible to make all of the lights flash (a single color) according to the beat using your code, sort of like what happens at 1:09 in the video.

Your code is super artsy, and it'd be great to have some variation in it as well, especially for long synth chords

**Comment by scottlawsonbc** [comment]
> I'm wondering if it's possible to make all of the lights flash (a single color) according to the beat using your code, sort of like what happens at 1:09 in the video.

It's certainly possible to do that, and it is very easy to set all of the pixels to the same color. The challenge is writing down an explicit mathematical function that returns the perceived salience of the beat.

I've spent many hours trying to make a decent visualizer using a non-addressable LED strip (i.e. every pixel being the same color), but I've never been happy with the results. It's easy to fine tune the visualization for a particular song, but the visualization tends to only work well for a limited range of music and is not robust.

I'm curious, why would you want to set every pixel to the same color?

**Comment by KaitoKid** [comment]
I've been trying to think of use cases for this project, and I wanted to try and demo it at house/frat parties at the university, but its gotten pretty boring due to how it feels like it does a single type of visualization. The word I guess I should've used for my issue is that I'm looking for **variety**.

Occasionally, if we could switch between 'visualization configurations', it could make the project a lot more exciting in a party sense. I suppose I'm looking for that could be as exciting as the light show for a rave. A good example is [the Shelter tour](https://www.youtube.com/watch?v=6C880_JzUTw).

If you look at the light and how it's synced up with the beat and synths at timestamps 20:30, 20:40, 37:30, 53:23, they have different 'configurations'. I realize that these are all manual, but I was hoping to simulate these. 

---

For the 'all LEDs on and pulsing to the beat', I originally thought about putting the sound through a low pass filter for xx frequency, and triggering if the volume is over a certain level.

I had hoped to maybe control different configs manually through an android app and sending HTTP requests to a server set up on an RPi. Hopefully I can work something out and get a demo vid of it for a party
