### ISSUE TITLE
Random lags and freeze in leds

### ISSUE THREAD

**Issue by ashii25** [scottlawsonbc/audio-reactive-led-strip#331]
Every things work fine but there are some random stutter and freeze in led while visualization there is not fps drop in visualization.. its mostly in leds..but there is ocassional freeze in visualization which shows up in led but frequent lags and stutter are not present in visualization but present in led strip with lagging and freezing..

**Comment by joeybab3** [comment]
Yeah that seems to be a wifi issue, but I was never able to figure out if it was client side, server side, or just a latency issue caused by the router.
