### ISSUE TITLE
having issue when install pyaudio --- Microsoft C++ Build Tools

### ISSUE THREAD

**Issue by ZelkerD** [scottlawsonbc/audio-reactive-led-strip#336]
Hi there, 

I'm a newbie to dev envir, not sure if anything wrong.

Win10 17134.1130
Python 3.8.8

I've succefully done :
Anaconda + 8266 addon
conda install numpy scipy pyqtgraph

But when I did "pip install pyaudio", something wrong as below:
--------------------------------------------------------------------------
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\IoT\ESP8266\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Freeb\\AppData\\Local\\Temp\\pip-install-n5p6ot1_\\pyaudio_775419936f824901bfe7eb2cac4dcdf3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Freeb\\AppData\\Local\\Temp\\pip-install-n5p6ot1_\\pyaudio_775419936f824901bfe7eb2cac4dcdf3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Freeb\AppData\Local\Temp\pip-wheel-rlwvrp64'
       cwd: C:\Users\Freeb\AppData\Local\Temp\pip-install-n5p6ot1_\pyaudio_775419936f824901bfe7eb2cac4dcdf3\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying src\pyaudio.py -> build\lib.win-amd64-3.8
  running build_ext
  building '_portaudio' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'E:\IoT\ESP8266\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Freeb\\AppData\\Local\\Temp\\pip-install-n5p6ot1_\\pyaudio_775419936f824901bfe7eb2cac4dcdf3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Freeb\\AppData\\Local\\Temp\\pip-install-n5p6ot1_\\pyaudio_775419936f824901bfe7eb2cac4dcdf3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Freeb\AppData\Local\Temp\pip-record-ruwnyqil\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\IoT\ESP8266\Anaconda\Include\pyaudio'
         cwd: C:\Users\Freeb\AppData\Local\Temp\pip-install-n5p6ot1_\pyaudio_775419936f824901bfe7eb2cac4dcdf3\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying src\pyaudio.py -> build\lib.win-amd64-3.8
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\IoT\ESP8266\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Freeb\\AppData\\Local\\Temp\\pip-install-n5p6ot1_\\pyaudio_775419936f824901bfe7eb2cac4dcdf3\\setup.py'"'"'; __file__='"'"'C:\\Users\\Freeb\\AppData\\Local\\Temp\\pip-install-n5p6ot1_\\pyaudio_775419936f824901bfe7eb2cac4dcdf3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Freeb\AppData\Local\Temp\pip-record-ruwnyqil\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\IoT\ESP8266\Anaconda\Include\pyaudio' Check the logs for full command output.
-------------------------------------------

I've installed Microsoft Build Tools 2015 as it shows in windows settings:
![image](https://user-images.githubusercontent.com/58769739/122660146-74bbbb00-d16e-11eb-967e-d29d9036b8e6.png)

However, it still failled to install. What should I do? pls help! Thanks!

**Comment by ZelkerD** [comment]
problem solved.... turns out it's not the correct tool that was downloaded from MS....

**Comment by ZelkerD** [comment]
close

**Comment by ZelkerD** [comment]
problem solved.... turns out it's not the correct tool that was download from MS....

And also, you'd better find a PyAudio‑0.2.11‑cp38‑cp38‑win_amd64.whl and put in Scripts folder in Anconda folder.

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio

**Comment by ZelkerD** [comment]
how to close this thread.....

**Comment by joeybab3** [comment]
If you've solved this issue, you can press "close with comment" or "close issue".
If not feel free to update this issue with details and someone may be able to help.
