### ISSUE TITLE
Maximum of 256 LEDs.

### ISSUE THREAD

**Issue by BennedYT** [scottlawsonbc/audio-reactive-led-strip#337]
I started looking at this project a few years ago and I've currently got everything up and running but I was intrested in if there will ever be an update to up the maximum for working with an ESP, since I haven't seen this change in the README eversince I started.

**Comment by joeybab3** [comment]
You are correct, it still has a 256 led limitation due to the packet size of 1024 (r * g * b * index * 256 = 1024).
It's in the backlog of things that I'd love to see if I can get to but I have not had time to work on this project besides occasional readme updates due to school.

**Comment by joeybab3** [comment]
#150 and #326 have some more discussion on this

**Comment by BennedYT** [comment]
Thank you for the information!
