### ISSUE TITLE
Grab album cover colours?

### ISSUE THREAD

**Issue by GeriTakeshi** [scottlawsonbc/audio-reactive-led-strip#341]
Hi, I absolutely love this project! I've been wandering whether there is a way so that the current album covers colours are grabbed and broadcasted to the LEDs. Can this be done automatically by getting colours from the cover file? I use foobar2000 if that helps whatsoever

**Comment by joeybab3** [comment]
I don't think that's in the scope of this library, it only pulls data in from the microphone and attempts to process it and send it to an led strip.

You could use the network transport layer as a starting point for making your own project that does what you are asking but I don't have much else in the way of assistance for you, unfortunately.
