### ISSUE TITLE
ESP8662 Not Lighting Up The LEDS 

### ISSUE THREAD

**Issue by St3v3EXE** [scottlawsonbc/audio-reactive-led-strip#353]
I'm using a esp8662, have followed all the steps and I get nothing, no lights, The GUI and audio detection works perfectly and it shows that it is running at 60+ FPS, but non of the lights are working. I just bought the ESP8662 so I doubt its a hardware problem. Is there anything that I can do to get it working. I have it working on my RPI but I would like to connect it to my ESP8662

**Comment by whytox** [comment]
Hi, I bought a node mcu v3 and it is working. Did you connect the data pin to the RX pin of the board?
What steps did you actually perform?

**Comment by St3v3EXE** [comment]
Hi. I have got the pin connected into the RX pin. I followed all the steps in the guild attached to the project. Its almost like my computer is not talking to my ESP8662, even though I've set the password and all the IP addresses.

**Comment by whytox** [comment]
So did you correctly set up the config files? The board IP address must be configured into the config.py too.

**Comment by St3v3EXE** [comment]
Yes I have set up the IP to be the same in the Config.py and the Arduino, and still nothing. I have WIFI and password set on the Arduino. I don't know if this helps but when I open the serial monitor it just gives me "⸮" every couple of seconds.  Also when I upload the code to the ESP the first 12 LED's light up then go off. It's like my pc is not talking to the ESP.

**Comment by joeybab3** [comment]
1. Are you sure the sketch uploaded properly?
2. Enable FPS output, this will tell you if the frames are getting to the arduino properly to help diagnose where the issue is

**Comment by St3v3EXE** [comment]
I'm pretty sure I uploaded it correctly while uploading the ESP was flashing ( which to my knowledge means that is is uploading correctly?). Also The FPS out put is on on both the Arduino and GUI, But in the Arduino serial monitor all it shows is "⸮".

This is what I have my Arduino upload set as ( If this helps at all)
![Arduino config](https://user-images.githubusercontent.com/99558633/155274247-33c2b1fa-2bf8-4be1-ac07-641c68582a02.png)

**Comment by St3v3EXE** [comment]
UPDATE. I got it working for some reason my the IP on my ESP was a fixed one and after finally seeing that my bit rate was not correctly set it all started working. Thank you for all the help you gave me it helped me find out what was wrong.
