### ISSUE TITLE
fatal error: WebSocketsServer.h: No such file or directory

### ISSUE THREAD

**Issue by potentstudios** [scottlawsonbc/audio-reactive-led-strip#36]
I'm really new to this so I'm not sure why it won't compile.

Error compiling for board NodeMCU 1.0 (ESP-12E Module).
...fatal error: WebSocketsServer.h: No such file or directory

 #include <WebSocketsServer.h>

                              ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by joeybab3** [comment]
DId you install the websockets library?
If not you can open library manager and search websockets and install it from there.

**Comment by potentstudios** [comment]
Perfect. Thanks so much!
