### ISSUE TITLE
How do you send to multiple nodeMCUs?

### ISSUE THREAD

**Issue by potentstudios** [scottlawsonbc/audio-reactive-led-strip#37]
How do you send to multiple nodeMCUs?

**Comment by d-rez** [comment]
You use broadcasting sir. Might need some code adjustments and/or keeping our NodeMCUs on a separate subnet, just sending packets to the broadcast IP address made my strip react but performance was horrible compared to unicast

**Comment by joeybab3** [comment]
Would it be possible to use websockets for this?  Because as far as I know you could scale this to a few arduinos if you could implement it over websockets.

**Comment by joeybab3** [comment]
This is not currently supported by this project but might be in a future release.
