### ISSUE TITLE
How to setup repo

### ISSUE THREAD

**Issue by Khushal-dalal** [scottlawsonbc/audio-reactive-led-strip#381]
I'm totally new to git, i download anaconda as written in the tutorial and installed the dependencies but i don't know how to setup the repository, like where to put those (dsp, config,led...) .py files ? I know how to setup the arduino .ino file
And i'm also looking for ditching anaconda for vs code because i have worked in it before but still, can someone help me setup those files?

**Comment by joeybab3** [comment]
A few things here:
1. Use git clone from within conda and then cd to the directory, this will make it easier to find it. 
2. You can still use vscode to edit the files and run them from within conda

**Comment by Khushal-dalal** [comment]
hey, thanks for your advice but now i kinda figured it out
1. i used conda with vs code (i set the python interpreter in vs code to where i installed python in conda v-env )
2. then i put all the project files in the v-env (not very practical way but conda wasn't searching for the files outside the v-env directory )
3.then i ran into many problems like error installing pyaudio, (pyqtgraph.Qt.QtGui' has no attribute 'QApplication) and much more
4. i fugured them out using windows copilot and now the visualization.py is running

**Comment by Khushal-dalal** [comment]
and also i fixed this error (pyqtgraph.Qt.QtGui' has no attribute 'QApplication) by installing 0.11.0 version of pyqtgraph

**Comment by Khushal-dalal** [comment]
i have one more question (i currently don't have esp8266 but i've ordered it) after setting up all the connections to the esp board and led strip, how will the visualization be sent to the led strip via wifi, like which program is responsible for this operation?

**Comment by joeybab3** [comment]
> i have one more question (i currently don't have esp8266 but i've ordered it) after setting up all the connections to the esp board and led strip, how will the visualization be sent to the led strip via wifi, like which program is responsible for this operation?

The python script sends frames over udp to the arduino
