### ISSUE TITLE
Test the LED strip

### ISSUE THREAD

**Issue by gscott1962** [scottlawsonbc/audio-reactive-led-strip#43]
I have 2 problems the first one is that I cant get the pi to recognize the usb audio? the 2nd one is when I run the sudo python strandtest.py only half of the leds come on but have no pattern just ramdom blinking doesn't start at the beginning of the strip or at the end also stops blinking then turns back on?

**Comment by gscott1962** [comment]
would lack of power do that?

**Comment by joeybab3** [comment]
In my experience, lack of power will give me either really dim green and blue less and only really red... it's possible you have a grb type strand and are sending the rgb code, I can't remember what I did but I had the same issue as you a while ago

**Comment by gscott1962** [comment]
This is all over the place very bright all of the colors but not pattern just random flshing?


Sent from Mail for Windows 10
