### ISSUE TITLE
Arduino uno support

### ISSUE THREAD

**Issue by erickho123** [scottlawsonbc/audio-reactive-led-strip#45]

**Comment by joeybab3** [comment]
How would this work, like over serial?

**Comment by erickho123** [comment]
Yes I was hoping serial

**Comment by scottlawsonbc** [comment]
Can you provide a bit more information about your request for Arduino Uno support? Are you wanting the code to run on the Uno standalone? (unlikely to be possible) Or are you wanting the Uno to act like the Node MCU, and the audio processing code would run on a computer? (would be possible)

**Comment by erickho123** [comment]
@scottlawsonbc the audio processing code would be on the computer and it would communicate through serial

**Comment by ManuelLevi** [comment]
I just created a "issue" about the serial communication. It's working on a Nano with a very small (8 led) ring. I can't test with a larger array as I don't have one right now. There's nothing I can think of preventing it from working with a Uno as well.

**Comment by joeybab3** [comment]
Combining serial related discussion to #52
