### ISSUE TITLE
Support of WS2801

### ISSUE THREAD

**Issue by QR47** [scottlawsonbc/audio-reactive-led-strip#47]
Very nice project!

Is it possible to convert your code to work with the WS2801 LED's?
I've some left from a Hyperion-project and would like to use them with a Pi ZeroW.

**Comment by joeybab3** [comment]
This would be possible by implementing the fastled library, but using the current implementation or the planned neopixelbus that I just submitted a pr request for, it wouldn't.

**Comment by Poolitzer** [comment]
Hey there,  #10 said that this was possible using fastled. Can you add that? Or is there a easy way for me as someone how is able to do a little bit programming, but not really much?

**Comment by joeybab3** [comment]
This should be possible using the current implementation which doesn't use the custom ws2812 library anymore.
