### ISSUE TITLE
Visualization.py and config.pi wher do i find them and where do they go? I have finally got leds to light in strandtest now im stuck please help?

### ISSUE THREAD

**Issue by gscott1962** [scottlawsonbc/audio-reactive-led-strip#48]

**Comment by gscott1962** [comment]
where do i find them and where do they go? I have finally got leds to light in strandtest now im stuck please help?

**Comment by joeybab3** [comment]
Have you tried redownloading the files from github?

**Comment by gscott1962** [comment]
I know where the file is but what is the command to get it?


Sent from Mail for Windows 10

**Comment by gscott1962** [comment]
Ok I cloned this file on raspberry and its in its own directory do I need to move it? I can find the directory in the terminal and I can find the visualization.py but I cant run it?

**Comment by gscott1962** [comment]
Ok I have gotten a little farther I guess when I run visualization.py I get this error?
Traceback (most recent call last):
  File "visualization.py", line 257, in <module>
    import pyqtgraph as pg
ImportError: No module named pyqtgraph

**Comment by joeybab3** [comment]
Did you follow the tutorial? Run pip install pyqtgraph I think is the command, there's a number of them, just follow the tutorial.

**Comment by gscott1962** [comment]
Installation for Raspberry Pi
If you encounter any problems running the visualization on a Raspberry Pi, please open a new issue. Also, please consider opening an issue if you have any questions or suggestions for improving the installation process.
Installing the Python dependencies
Install python dependencies using apt-get
This is the guide I am following its Scott lawsons and in here he doesn't mention Pyqtgraph he does in other dependency's and yes I followed the guide yes I am new at this and no I'm not stupid?
sudo apt-get update
sudo apt-get install python-numpy python-scipy python-pyaudio
Install ws281x library
To install the ws281x library I recommend following this Adafruit tutorial.
sudo apt-get install build-essential python-dev git scons swig
git clone https://github.com/jgarff/rpi_ws281x.git
cd rpi_ws281x
scons
 when I run the visualization.py it says it cant find the file but when I go to install it pi says its already there?

**Comment by RichusX** [comment]
Did you ```cd python``` into the directory before trying to launch it?

**Comment by gscott1962** [comment]
Yes that’s what is confusing me I can find it I can open it its in the same place most everything else is but when I run visualization.py it starts the window then stop saying it cant find the mentioned file? Going to redo everything on another sd card and see what happens then compare the two?
 

Sent from Mail for Windows 10

**Comment by gscott1962** [comment]
can you tell me which dir. the visualization file should be installed to?

**Comment by gscott1962** [comment]
You are not going to believe this but I have the visualization.py running and it actually is reading the music in the screen ! But I cant figure out why I have no leds? I have checked the wiring 2 times? Any ideas?

**Comment by gscott1962** [comment]
Fron python folder to python flolder?


Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Ritvars <notifications@github.com> Date: 5/28/17  10:46 AM  (GMT-05:00) To: scottlawsonbc/audio-reactive-led-strip <audio-reactive-led-strip@noreply.github.com> Cc: gscott1962 <gscott1962@brighthouse.com>, Author <author@noreply.github.com> Subject: Re: [scottlawsonbc/audio-reactive-led-strip] Visualization.py and
  config.pi wher do i find them and where do they go? I have finally got leds to
  light in strandtest now im stuck please help? (#48) 
Did you cd python into the directory before trying to launch it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/scottlawsonbc/audio-reactive-led-strip","title":"scottlawsonbc/audio-reactive-led-strip","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/scottlawsonbc/audio-reactive-led-strip"}},"updates":{"snippets":[{"icon":"PERSON","message":"@RichusX in #48: Did you ```cd python``` into the directory before trying to launch it?"}],"action":{"name":"View Issue","url":"https://github.com/scottlawsonbc/audio-reactive-led-strip/issues/48#issuecomment-304519503"}}}
