### ISSUE TITLE
Wifi connection problems

### ISSUE THREAD

**Issue by tab26715** [scottlawsonbc/audio-reactive-led-strip#57]
Running the controller program on the esp8266 will print "Connected to [network name]" and the IP address underneath in the serial monitor, however the board does not appear on the router's list of connected devices and led.py will not display on the LEDs. Any ideas? I also have one other, possibly related question: Is there a method to picking an IP address for the esp8266, or is it pretty much up to you?

**Comment by joeybab3** [comment]
Does the ip address printed match your local ip scheme?

**Comment by tab26715** [comment]
It matches what I used in config.py and the controller file, but I'm not sure if the mostly random address I used there matches what you mention. Can you explain the local ip scheme thing?

**Comment by joeybab3** [comment]
If you are using windows, type "ipconfig" in cmd prompt(type cmd into the start menu) and report back what it says under ipv4 address (most likely a 192.168.x.x or 10.x.x.x number)

**Comment by tab26715** [comment]
10.0.0.14

**Comment by joeybab3** [comment]
Alright, does the ip you gave the ESP look similar in the 10.0.0.x respect?

**Comment by tab26715** [comment]
It wasn't but I changed it and it seems to be working now, Thank you!

**Comment by joeybab3** [comment]
You're welcome!
