### ISSUE TITLE
Stuttering in scroll effect

### ISSUE THREAD

**Issue by tab26715** [scottlawsonbc/audio-reactive-led-strip#58]
I saw that this issue has been brought up before, but I don't think it reached a clear conclusion. When I run the visualization with scroll effect, it cycles through ~5 second intervals of smooth animation followed by noticeably choppy ones, however the visualization.py fps counter doesn't show a corresponding drop in frames. Is there an easy fix for this?

**Comment by joeybab3** [comment]
What hardware are you using?

**Comment by tab26715** [comment]
NodeMCU esp8266 and ws2812b LEDs

**Comment by joeybab3** [comment]
Ok, if you have print_fps set to 1, what does it show on the serial monitor?

**Comment by tab26715** [comment]
60 fps minimum, mostly hits high sixties, plus drops in frame rate do not correspond very well with the stuttering. It seems like the behavior happens on a regular time cycle.

**Comment by joeybab3** [comment]
Do you have another pc to test it on? I want to figure out if it's client or server side.

**Comment by tab26715** [comment]
Unfortunately I don't, hopefully I'll have the opportunity to try that soon

**Comment by joeybab3** [comment]
Ok. One more thing you could try, under the line that looks like this in the arduino sketch:
```
 #if PRINT_FPS
        fpsCounter++;
#endif
```

add the line: `Serial.print("/");//Monitors connection(shows jumps/jitters in packets)` So that it looks like this:
```
 #if PRINT_FPS
            fpsCounter++;
            Serial.print("/");//Monitors connection(shows jumps/jitters in packets)
#endif
```

and check if the stutters match up with the /////'s being printed

**Comment by tab26715** [comment]
Thanks for your continued help. Looking at the serial monitor with that code shows plenty of /'s, but they appear both when the animation is smooth and choppy. They did help illustrate a pattern in fps however. Attached is a picture of a section of serial output.
![img_0689](https://user-images.githubusercontent.com/21126779/28252846-b97c5a76-6a69-11e7-9999-3a38423b9a17.JPG)
The animation will get smooth and was promptly followed by "fps: 127". It remained smooth briefly then as soon as it stuttered "fps: 114" showed up. It was then choppy until just before "fps: 126" appeared. This pattern pops up frequently regardless of song but only really when running the scroll effect.
![img_0688](https://user-images.githubusercontent.com/21126779/28252941-1e7bea76-6a6b-11e7-94c2-05a3b8e472d9.JPG)

**Comment by tab26715** [comment]
Ok so actually very simple solution. I finally got around to putting a sizable (1000uf) capacitor in for power smoothing and it seems to have done the trick! Crazy how much it helps actually, I had no idea. Thanks again for your help.
