### ISSUE TITLE
Why is the WebSocketsServer library included?

### ISSUE THREAD

**Issue by joeybab3** [scottlawsonbc/audio-reactive-led-strip#60]
So after trying to port this to the esp32 (Which I was successful ;) I was having issues with it complaining about the ethernet library which I figured shouldn't be in there anyway so i looked to see what was requiring it, and it was the websocketserver library. I commented that line out(where it's included) and it still compiles, and works, both on the esp8266 and the esp32...Is there a reason we're including it, or is it just left over from something in the past? if it's truly not necessary, let me know and i'll submit a pr.

**Comment by scottlawsonbc** [comment]
Yes I think you are correct, the library is not needed and the import can be removed. Please submit a PR and I will merge it.

**Comment by joeybab3** [comment]
Done
