### ISSUE TITLE
trouble compiling ws2812_controller.ino

### ISSUE THREAD

**Issue by chafikchaban** [scottlawsonbc/audio-reactive-led-strip#65]
Hi all , i'm new to the ESP modules . i'm using the NodeMCU board.

when i try to compile the ws2812_controller.ino , i get this error : 

** 
 #include ws2812_i2s.h
 compilation terminated.

 exit status 1
 Error compiling for board NodeMCU 1.0 (ESP-12E Module).**  

any help will be appreciated .

![image](https://user-images.githubusercontent.com/30408070/28522098-8c3bc250-702b-11e7-98c3-06e0c2d6c868.png)

**Comment by Froggy03** [comment]
Have you installed the CH340 driver? Google it its the first link.

Before plugging the nodemcu in hold the flash pushbutton then release once plugged in.

I flash mine using 160Mhz. 

Hope this helps

**Comment by joeybab3** [comment]
You copied and pasted the code from the controller into the blink sketch? Try pressing "Clone or download", then "Download ZIP" on the project page. It has all the libraries needed bundled.

The other option is to use my fork, which uses the neopixelbus library:
[https://github.com/joeybab3/audio-reactive-led-strip/blob/master/arduino/ws2812_controller/ws2812_controller.ino](https://github.com/joeybab3/audio-reactive-led-strip/blob/master/arduino/ws2812_controller/ws2812_controller.ino)
