### ISSUE TITLE
Use analog input for volume on ESP8166?

### ISSUE THREAD

**Issue by CRCinAU** [scottlawsonbc/audio-reactive-led-strip#7]
Would be nice to just be able to have a 0-1v input on the ESP8166 to drive the whole thing.

Would something like this be adaptable?
http://yaab-arduino.blogspot.com.au/2015/02/fast-sampling-from-analog-input.html

**Comment by scottlawsonbc** [comment]
Thanks for the suggestion. Can you clarify what you mean by volume?

Right now the ESP8266 does not process any audio data. All signal processing is done on a computer and pixel information is transmitted to the ESP8266 over wifi.

It would be possible to use the ESP8266's ADC pin for something, but I'm a bit confused by your suggestion. What could it be used for?

**Comment by CRCinAU** [comment]
I'm wondering if the ADC could be used to create the spectral data instead of having a PC do it?

**Comment by scottlawsonbc** [comment]
Unfortunately the ESP8266 is much too slow to do the signal processing by itself. It might be possible if the code was ported to C++, but it would be easier to just use a faster computer like the Raspberry Pi.

**Comment by kevinpanaro** [comment]
@CRCinAU like this? https://github.com/cnlohr/colorchord

**Comment by CRCinAU** [comment]
Ooooo. Yup.

I wonder if some of those features could be added into the ESP of this project?

**Comment by scottlawsonbc** [comment]
The ESP8266 would be too slow to run the visualization unless the code was ported from Python to C++, but even then still I'm not sure if it would be fast enough. This would take a lot of time and I don't have plans to do this in the foreseeable future.

For a standalone unit, is there any particular reason why would you want to use an ESP8266 instead of a Raspberry Pi?

**Comment by CRCinAU** [comment]
Not really - tbh I don't have any ESP gear - but was opening up the discussion as I figured it would be awesomely neat to have it all self-contained in a tiny package. As such, it was purely for the technical possibility conversation.

**Comment by scottlawsonbc** [comment]
Thanks, I appreciate your suggestion. I'll close this issue for now because I don't have plans to support the ESP8266 as a standalone unit. Please feel free to open more issues if you have other suggestions. I'm always looking for ways to improve the project.
