### ISSUE TITLE
regarding the RX  pin in esp01 module

### ISSUE THREAD

**Issue by giri110890** [scottlawsonbc/audio-reactive-led-strip#74]
Hi Scott,

I have researched for quite few days after you mentioned that few modules like esp01 cannot be used in the document. But later after reading few specifications and me trying out myself i found out the esp01 can also be used and it works fine.

**Comment by d-rez** [comment]
Did he say that?

I've been running it fine on ESP-01 since like Feb. #34

**Comment by giri110890** [comment]
The below was written under Hardware Connections from his documentation :

_The ESP8266 has hardware support for I²S and this peripheral is used to control the ws2812b LED strip. This signficantly improves performance compared to bit-banging the IO pin. Unfortunately, this means that the LED strip must be connected to the RX1 pin, which is not accessible in some ESP8266 modules (such as the ESP-01)._

**Comment by joeybab3** [comment]
Yeah I can submit a pr to update the documentation but Scott hasn’t been active in a while so I’m not sure it’ll be looked at for a bit.

**Comment by scottlawsonbc** [comment]
What configuration / code changes are needed in order to make this work with the ESP-01? I'll update the documentation

**Comment by thalesvon** [comment]
Hi @giri110890, did you have to change anything in the code to work with the ESP01?

**Comment by giri110890** [comment]
Hey Thales,

No there's no change in the code and the data wire for the led strip should
be connected to the Rx pin of the Esp01 module.
