### ISSUE TITLE
music visualuzer for android connected led

### ISSUE THREAD

**Issue by sahaab** [scottlawsonbc/audio-reactive-led-strip#75]
hey, i am trying to do this exact same thing, but instead connected to an android application and transmitted via wifi (using chip wemos d1 mini).

So far, i have gotten it to show a FFT spectrum, now my problem is that, how can i make it show the MEL filterbank spectrum like yours, yours looks much cooler and im guessing thats due to the MEL filterbank.

(I want to use the spectrum view)

**Comment by joeybab3** [comment]
So to get this straight, you want to run the microphone/server on the phone but still have the leds on the wemos d1 mini?

**Comment by sahaab** [comment]
Yep

**Comment by joeybab3** [comment]
Ok, have you tried your hand at porting the filter bank code to android or are you asking for someone else to?

**Comment by joeybab3** [comment]
Or: have you tried python-for-android?

**Comment by sahaab** [comment]
thank you for the help, I have not ported it or tried, but I have gotten something made that is similar, I will probably post it on github when i have a better version and build of it done.
thank you

**Comment by ToXIc-Dev** [comment]
@sahaab Any update on this?

How did you get it to show the FFT spectrum?

**Comment by sahaab** [comment]
> @sahaab Any update on this?
> 
> How did you get it to show the FFT spectrum?

Sorry I was never able to get a good audio visualizer working. Due to the restriction of android now not being able to read background music playing from the app, I had to use the mic, and the lowest the mic records is around 4000Hz, which doesnt give a pretty good visualization. I do have an IOT type setup done with the app, and audio visualization is there but its not good or close.

**Comment by ToXIc-Dev** [comment]
> > @sahaab Any update on this?
> > How did you get it to show the FFT spectrum?
> 
> Sorry I was never able to get a good audio visualizer working. Due to the restriction of android now not being able to read background music playing from the app, I had to use the mic, and the lowest the mic records is around 4000Hz, which doesnt give a pretty good visualization. I do have an IOT type setup done with the app, and audio visualization is there but its not good or close.

Is that a new restriction of Android as im on Android 10 on my Galaxy S9 and [this app](https://github.com/Ipsedo/Spectrix) is able to get the music stream and show a spectrum.

**Comment by sahaab** [comment]
It may be my own phones but pretty sure android 9 had it.
You sure it doesn't use your mic?

**Comment by ToXIc-Dev** [comment]
> It may be my own phones but pretty sure android 9 had it.
> You sure it doesn't use your mic?

Yep, there is a setting in the app to switch between stream and mic and when I pause Spotify while stream is selected the spectrum disappears completely.

**Comment by sahaab** [comment]
> > It may be my own phones but pretty sure android 9 had it.
> > You sure it doesn't use your mic?
> 
> Yep, there is a setting in the app to switch between stream and mic and when I pause Spotify while stream is selected the spectrum disappears completely.

Hmm well its best to research on this some more then

**Comment by ToXIc-Dev** [comment]
> > > It may be my own phones but pretty sure android 9 had it.
> > > You sure it doesn't use your mic?
> > 
> > 
> > Yep, there is a setting in the app to switch between stream and mic and when I pause Spotify while stream is selected the spectrum disappears completely.
> 
> Hmm well its best to research on this some more then

I'm a complete noob when it comes to Android programming but i'll try to see what I can do myself, did you mean you're going to research it some more?

**Comment by sahaab** [comment]
> > > > It may be my own phones but pretty sure android 9 had it.
> > > > You sure it doesn't use your mic?
> > > 
> > > 
> > > Yep, there is a setting in the app to switch between stream and mic and when I pause Spotify while stream is selected the spectrum disappears completely.
> > 
> > 
> > Hmm well its best to research on this some more then
> 
> I'm a complete noob when it comes to Android programming but i'll try to see what I can do myself, did you mean you're going to research it some more?

Yes ill check too as soon as i can

**Comment by ToXIc-Dev** [comment]
@sahaab I've had a look at the code and think it shouldn't be too hard to edit the app so it sends UDP packets to the ws2812_controller.ino or [WLED](https://github.com/Aircoookie/WLED) (This is what I am planning on using it with) 

As I said im a complete noob with android and also UDP, so i'm having a bit of trouble figuring out how it all works, (Can't seem to get UDP to work when trying with a sender app, im probably doing it wrong)

**Comment by joeybab3** [comment]
At the moment android integration/support is out of the scope of this project, feel free to continue discussing it though.
