### ISSUE TITLE
WS2811

### ISSUE THREAD

**Issue by Arthur266** [scottlawsonbc/audio-reactive-led-strip#77]
Hi guys
I need some help. What i must change to get the ws2811 strip to work with the wlan module and pc ?
Thank you )

**Comment by joeybab3** [comment]
See my fork/PR, I use a different ws2812 library which should also support the ws2811

**Comment by richyxi** [comment]
hi @joeybab3 its the neopixelbus library?

**Comment by joeybab3** [comment]
It's been merged since my last comment, try it out and let me know.
