### ISSUE TITLE
led_test changes 3 led's instead of 1

### ISSUE THREAD

**Issue by davehun** [scottlawsonbc/audio-reactive-led-strip#80]
i have set 
N_PIXELS = 48 in config.py and #define NUM_LEDS 48
in ws2812_controller.ino however the test led.py program causes 9 led's to be lit up rather than 3.
each group of 3 shares the same colour.
running on osx if that helps 
you can see from the udp packet here that the packet sent looks correct but this results in led's 1 2 and 3 being red. 4,5 and 6 blue and 7 8 and 9 bing green!
  
  00:ff:00:00:01:00:ff:00:02:00:00:ff:03:00:00:00:04:00:00:00:05:00:00:00:06:00:00:00:07:00:00:00:08:00:00:00:09:00:00:00:0a:00:00:00:0b:00:00:00:0c:00:00:00:0d:00:00:00:0e:00:00:00:0f:00:00:00:10:00:00:00:11:00:00:00:12:00:00:00:13:00:00:00:14:00:00:00:15:00:00:00:16:00:00:00:17:00:00:00:18:00:00:00:19:00:00:00:1a:00:00:00:1b:00:00:00:1c:00:00:00:1d:00:00:00:1e:00:00:00:1f:00:00:00:20:00:00:00:21:00:00:00:22:00:00:00:23:00:00:00:24:00:00:00:25:00:00:00:26:00:00:00:27:00:00:00:28:00:00:00:29:00:00:00:2a:00:00:00:2b:00:00:00:2c:00:00:00:2d:00:00:00:2e:00:00:00:2f:00:00:00

**Comment by d-rez** [comment]
Some LED strips are just made this way and only do 3 LEDs at once. Check with your led strip data specs. This is not a fault with the code
