### ISSUE TITLE
NodeMCU would not connect to WiFi

### ISSUE THREAD

**Issue by gannaramu** [scottlawsonbc/audio-reactive-led-strip#82]
Hey,
I was trying to implement your project but my NodeMCU wouldn't connect to my WiFi (WPA-PSK)
I was running it on Arduino IDE 1.8.5
Esp8266 v2.3.0 
NodeMCU lolin V3

**Comment by d-rez** [comment]
Well... Did you configure your SSID/PASS/IP/GATEWAY etc. correctly?

**Comment by joeybab3** [comment]
Can you give us a little more info?

**Comment by gannaramu** [comment]
Hey,

I had figured it out by changing my router configuration. It was not able to assign the ip address. It's working now. But at times it still doesn't connect at a single go.

**Comment by pandaDS3** [comment]
had the same mistake, choose NodeMCU 1.0 (ESP-12E). it helped me

**Comment by joeybab3** [comment]
Can you close this if it’s solved?
