### ISSUE TITLE
RPI3 Failed to connect to X Server

### ISSUE THREAD

**Issue by Malle355** [scottlawsonbc/audio-reactive-led-strip#92]
Hi Guys,

just installed everything on the Pi3. When I run the virualization.py it says "failed to connect to X Server". Any Ideas? Is there also a proper manual how to get it on the PI working?

Thank you.

**Comment by web-rpi** [comment]
Please start the XServer in your terminal. Then you open a terminal the Xserver and start the visualizitation.py with sudo python visualizitation.py

Sorry for my realy bad english

Web-RPi

**Comment by Malle355** [comment]
What is xserver? Sorry I haven't that much experience with the raspberry. I am using raspbian stretch lite.

**Comment by web-rpi** [comment]
Hey,

you can edit the visualization.py line 251 from 

visualization_effect = visualize_scroll

To

visualization_effect = visualize_spectrum
 
then you can start it without gui with the "spectrum"-effect.
