### ISSUE TITLE
Scroll Effect.

### ISSUE THREAD

**Issue by Malle355** [scottlawsonbc/audio-reactive-led-strip#93]
Anyone got the Scroll Effect like in the Sample Video? My Scroll Effect is to fast and seems very strange.

**Comment by joeybab3** [comment]
I’ve had similar effects, his does seem to work strangely well, but it’s also an old video. Post a video here of what you are experiencing and I can try and look at it.

**Comment by scottlawsonbc** [comment]
Does changing the FPS in the configuration file affect the scrolling speed?

**Comment by rbirkby** [comment]
https://www.youtube.com/watch?v=lj1yhpyGnT4

**Comment by joeybab3** [comment]
It seems like your scroll effect is slower than his actually lol, and mine too for that matter. Alexa integration was cool though.

**Comment by d-rez** [comment]
More leds, longer strip = looks slower

[Here's mine](https://youtu.be/FoTgSMvDpUw?t=93), and [also here](https://youtu.be/QKsfK_zStsI?t=32)

**Comment by not-matt** [comment]
Again this will be changed soon, the rolling speed will be based off actual
time rather than a single np.roll every iteration loop.

**Comment by d-rez** [comment]
In your fork?

**Comment by not-matt** [comment]
That's where it will be when it's implemented yeah
