### ISSUE TITLE
No module named scipy

### ISSUE THREAD

**Issue by marnikmetten** [scottlawsonbc/audio-reactive-led-strip#94]
I get an error while running the visualization.py

it says 

Traceback (most recent call last):
  File "/home/pi/Desktop/audio-reactive-led-strip-master/python/visualization.py", line 5, in <module>
    from scipy.ndimage.filters import gaussian_filter1d
ImportError: No module named 'scipy'

Thanks in advance

**Comment by web-rpi** [comment]
Hey,

sudo apt-get install python-scipy

or

pip install scipy

Is your solution.

Web-RPi

**Comment by marnikmetten** [comment]
Hello again,
both solutions will not work

pi@raspberrypi:~ $ sudo apt-get install python-scipy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-scipy is already the newest version (0.18.1-2).
0 upgraded, 0 newly installed, 0 to remove and 149 not upgraded.


while doing pip install scipy gives me this error
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vXKyIP/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-E8RSED-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-vXKyIP/scipy/

**Comment by joeybab3** [comment]
Not sure, I can’t find much info on that. At this point all I can recommend is basic diagnostic steps, uninstalling everything to do with it, reinstalling. Installing all updates for everything.

**Comment by tc5368** [comment]
Did you try "sudo pip install scipy" ?
